const benchminorsRecord = [
    {'season':1, 'played':0, win_pct:-1, playoffs:"Inactive", text:"",
    'playoff-matchups':{"Play-in": "L - SPAP (7)"}},
    {'season':2, 'played':0, win_pct: -1, playoffs:"Inactive", text:"",
    'playoff-matchups':{"Play-in": "W - SPAP (5)",
                        "First Round": "L - R2L (7)"}},
    {'season':3, 'played':0, win_pct:-1, playoffs:"Inactive", text:"",
    'playoff-matchups':{"Play-in": "BYE",
                        "First Round": "W - TKL (6)",
                        "Semifinals":"W - R2L (4)",
                        "Finals":"L - SCOUT (7)"}},
    {'season':4, 'played':1, win_pct:0.125,playoffs:"Missed", text:"Under construction - season-by-season highlights coming soon!",
        'playoff-matchups':{}},
    {'season':5, 'played':1, win_pct:0.6, playoffs:"Semifinals", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{"Play-in":"BYE",
                        "First Round":"W - TKL (5)", 
                        "Semifinals":"L - COAST (4)"},
        'awards':{"ROTY":"Pierre-luc Dubois",
                  'All-stars':['P Dubois', "M Fleury"]}},
    {'season':6, 'played':1, win_pct:0.4, playoffs:"Play-in", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{"Play-in":"L - IRE (4)"}},
    {'season':7, 'played':1, win_pct:0.2, playoffs:"Missed", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{}},
    {'season':8, 'played':1, win_pct:0.1, playoffs:"Missed", text:"Under construction - season-by-season highlights coming soon!",
        'playoff-matchups':{"Play-in":"L - TRAP (5)"}},
    {'season':9, 'played':1, win_pct:0.7, playoffs:"Finals", text:"Under construction - season-by-season highlights coming soon!",
        'playoff-matchups':{"Play-in":"BYE",
                            "First Round":"L - PETE (3)",
                            "Semifinals":"W - TKL (5)",
                            "Finals":"L - SHAME (3)"},
        'awards':{"Lemon":[],"All-stars":['P Dubois',  'P Vala', 'P Grubauer']}}]

const checkersRecord = [
    {'season':1, 'played':0, win_pct:-1, playoffs:"Inactive", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{"Play-in": "L - SPAP (7)"}},
    {'season':2, 'played':0, win_pct: -1, playoffs:"Inactive", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{"Play-in": "W - SPAP (5)",
                        "First Round": "L - R2L (7)"}},
    {'season':3, 'played':1, win_pct:0.538, playoffs:"Champion", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{"Play-in": "BYE",
                        "First Round": "W - CHEESE (5)",
                        "Semifinals":"W - RUSS (4)",
                        "Finals":"W - SCOUT (7)",
                        "Champion":"S3 CHAMPION"},
        'awards':{"Champion":[], 'FMVP':"Klim Kostin", "COTY":"Nich Seyler" }},
    {'season':4, 'played':1, win_pct:0.22,playoffs:"Play-in", text:"Under construction - season-by-season highlights coming soon!",
        'playoff-matchups':{"Play-in": "L - IRE (4)"},
        'awards':{'COTY':"Nich Seyler"}},
    {'season':5, 'played':1, win_pct:0.6, playoffs:"First Round", text:"Under construction - season-by-season highlights coming soon!",
        'playoff-matchups':{"Play-in":"BYE",
                            "First Round": "L - TRAP (5)"},
                'awards':{"MIPOTY":"Klim Kostin", 'COTY':"Nich Seyler", "All-stars":["Klim Kostin"]}},
    {'season':6, 'played':1, win_pct:0.5, playoffs:"Play-in", text:"Under construction - season-by-season highlights coming soon!",
        'playoff-matchups':{"Play-in":"L - LOOK (3)"}},
    {'season':7, 'played':0, win_pct:-1, playoffs:"Inactive", text:"Under construction - season-by-season highlights coming soon!"},
    {'season':8, 'played':0, win_pct:-1, playoffs:"Inactive", text:"Under construction - season-by-season highlights coming soon!",
        'playoff-matchups':{"Play-in":"L - TRAP (5)"}},
    {'season':9, 'played':0, win_pct:-1, playoffs:"Inactive", text:"Under construction - season-by-season highlights coming soon!f",
        'playoff-matchups':{"Play-in":"W - CHEESE (3)",
                            "First Round":"L - TKL (3)"}}]


const cheeseRecord = [
    {'season':1, 'played':1, win_pct:0.67, playoffs:"Champion", text:"The Cheese join the Trap and Coasters as one of 3 teams to sign the original 202HL charter. After an emboldening 8-4 regular season, captain Mija Poblano leads her team through two Game 7 overtimes to hoist the first ever 202HL cup, earning Finals MVP with an extra-sharp 13-point Finals performance.",
    'playoff-matchups':{"Play-in": "BYE",
                        "First Round": "W - SPAP (7)",
                        "Semifinals": "W - LOOK (4)",
                        "Finals":"W - PING (7)",
                        "Champion": "S1 CHAMPION"},
    'awards':{'Champion':{'city':'Central', 'name':'Cheese'}, 'FMVP':'Mija Poblano', 'COTY':'Ben Artuso'}},
    {'season':2, 'played':1, win_pct: 0.38, playoffs:"First Round", text:"Despite Poblano’s best efforts, the party-hard Cheese slump into an embarrassing losing season and first-round playoff exit. ",
    'playoff-matchups':{"Play-in": "W - TRAP (4)",
                        "First Round": "L - LOOK (6)"},
    'awards':{'All-stars':['Sonny Milano']}},
    {'season':3, 'played':1, win_pct:0.543, playoffs:"First Round", text:"Beginning a return to form, the Cheese trend upwards in regular season play, but are bucked in the first round for the second straight year, winning only one game against the eventual champion Checkers.",
    'playoff-matchups':{"Play-in": "BYE",
                        "First Round": "L - CHECK (5)"},
    'awards':{'All-stars':['Mija Poblano']}},
    {'season':4, 'played':1, win_pct:0.800,playoffs:"Finals", text:"Mija Poblano breaks the hearts of Central fans by demanding a trade to the newly formed Montage Moment superteam. Against all odds, Zach Aston-Reese fills Poblano’s impossibly large shoes, finishing 2nd in MVP voting while leading the Cheese to first regular season title and a second Finals berth.",
        'playoff-matchups':{"Play-in": "BYE",
        "First Round": "W - IRE (5)",
        "Semifinals":"W - LOOK (7)",
        "Finals": "L - RUSS (4)"},
    'awards':{'Lemon':{'city':'Central', 'name':'Cheese'}, 'MIPOTY':'Zach Aston-Reese', 
        'All-stars':['Zach Aston-Reese']}},
    {'season':5, 'played':1, win_pct:0.777, playoffs:"First Round", text:"The Cheese continue to build depth, and are rewarded with a second regular season title in as many years. They immediately squander it by allowing their playoff nemeses (the Russia Russians) to sweep them in the first round.",
        'playoff-matchups':{"Play-in": "BYE",
        "First Round":"L - RUSS (4)"},
    'awards':{'Lemon':{'city':'Central', 'name':'Cheese'}, 'GOTY':'Philip Grubauer', 'All-stars':['Zach Aston-Reese', 'Philip Grubauer']}},
    {'season':6, 'played':1, win_pct:0.6, playoffs:"Finals", text:"With the much-anticipated signing of free agent Yanni Gourde, the Cheese make another Finals run, only to lose to the Russians again, in a THIRD straight postseason.",
        'playoff-matchups':{"Play-in": "BYE",
        "First Round": "W - TKL (6)",
        "Semifinals":"W - R2L (4)",
        "Finals":"L - SCOUT (7)"},
    'awards':{}
    },
    {'season':7, 'played':1, win_pct:0.8, playoffs:"First Round", text:"Despite the shrewd acquisition of star goaltender Marc-André Fleury, it is clear that the Cheese’s era of dominance is coming to an end. With several old-guard heroes retiring (most notably Aston-Reese, Milano, and Raddysh) and Appleton departing to join the Spappers in Salmon Arm, the Cheese begin a 3-season drought during which they will only win ONE playoff game.",
        'playoff-matchups':{"Play-in": "BYE",
        "First Round": "L - IRE (3)"},
        'awards':{'ROTY':'Cody Almond', 'All-stars':['Cody Almond', 'M Fleury']}},
    {'season':8, 'played':1, win_pct:0.5, playoffs:"First Round", text:"Fleury finishes second in Goalie of the Year voting, narrowly losing to the Shame Knights’ Scott Darling despite being protected by a vastly inferior defense. This is his third straight 2nd-place finish…",
        'playoff-matchups':{"Play-in":"BYE",
        "First Round":"L - LOOK (4)"},
        'awards':{'All-stars':['C Almond', "Y Gourde"]}},
    {'season':9, 'played':1, win_pct:0.5, playoffs:"Play-in", text:"Highs and lows for the Cheese in Season 9. Fleury pitches a record-breaking season and finally is crowned Goalie of the Year, while the rest of the team (through no fault of Fleury’s) are mercilessly swept in their first playoff series, marking their first ever failure to make it past the play-in round.",
        'playoff-matchups':{"Play-in":"L - SCOUT (3)"},
    'awards':{'GOTY':'Marc-Andre Fleury', 'All-stars':["M Fleury"]}}]



const coastersRecord = [
    {'season':1, 'played':1, win_pct:0.875, playoffs:"Semifinals", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{"Play-in": "BYE",
                        "First Round": "W - R2L (4)",
                        "Semifinals": "L - PING (5)"},
    'awards':{'Lemon':{}, 'DPOTY':'Dustin Byfuglien', 'GOTY':'Malcolm Subban'}},
    {'season':2, 'played':1, win_pct: 0.538, playoffs:"Semifinals", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{"Play-in": "BYE",
                        "First Round": "W - PING (4)",
                        "Semifinals": "L - LOOK (7)"},
    'awards':{'All-stars':['Dustin Byfuglien']}},
    {'season':3, 'played':1, win_pct:0.462, playoffs:"First Round", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{"Play-in": "W - LOOK (4)",
                        "First Round": "L - RUSS (4)"}},
    {'season':4, 'played':1, win_pct:0.5,playoffs:"First Round", text:"Under construction - season-by-season highlights coming soon!",
        'playoff-matchups':{'Play-in':"BYE",
        'First Round':'L - LOOK (4)'},
    'awards':{'All-stars':['Malcolm Subban', 'Something Brown']}},
    {'season':5, 'played':1, win_pct:0.5, playoffs:"Champion", text:"Under construction - season-by-season highlights coming soon!",
        'playoff-matchups':{
                "Play-in":"BYE",
                "First Round":"W - LOOK (4)",
                "Semifinals":"W - MONT (3)",
                "Finals":"W - RUSS (5)",
                'Champion':"S5 CHAMPION"},
        'awards':{'DPOTY':"Dustin Byfuglien", 'All-stars':['Something Nurse']}},
    {'season':6, 'played':1, win_pct:0.7, playoffs:"First Round", text:"Under construction - season-by-season highlights coming soon!",
        "playoff-matchups": {
            'Play-in':"BYE",
            'First Round':"L - LOOK (4)"
        },
        'awards':{'All-stars':['J Nurse', 'J Bowey']}},
    {'season':7, 'played':1, win_pct:0.5, playoffs:"First Round", text:"Under construction - season-by-season highlights coming soon!",
        "playoff-matchups":{
            "Play-in":"W - LOOK (5)",
            "First Round":"L - TRAP (4)"
        }},
    {'season':8, 'played':1, win_pct:0.6, playoffs:"Finals", text:"Under construction - season-by-season highlights coming soon!",
        'playoff-matchups':{
            "Play-in":"BYE",
            "First Round":"W - CHEESE (3)",
            "Semifinals":"W - SHAME (3)",
            "Finals":"L - PETE (3)"},
        'awards':{'All-stars':['David Bowey']}},
    {'season':9, 'played':1, win_pct:0.5, playoffs:"First Round", text:"Under construction - season-by-season highlights coming soon!",
        'playoff-matchups':{"Play-in":"BYE",
                            "First Round":"L - TRAP (3)"},
        'awards':{'MVP':"Bobby Earl"}}]


const hatLookersRecord = [
    {'season':1, 'played':1, win_pct:0.478, playoffs:"Semifinals", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{"Play-in": "L - RUSS (4)",
                        "First Round":"REVIVED!",
                        "Semifinals":"L - CHEESE (4)"}},
    {'season':2, 'played':1, win_pct: 0.846, playoffs:"Champion", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{"Play-in": "BYE",
                        "First Round": "L - CHEESE (6)",
                        "Semifinals":"W - COAST (7)",
                        "Finals":"W - R2L (4)",
                        "Champion":"S2 CHAMPION"},
    'awards':{'Champion':[], 'FMVP':'Derek Stepan', "Lemon":[], "GOTY":"Pekka Rinne",
            'All-stars':['Pekka Rinne', 'Clayton Keller']}},
    {'season':3, 'played':1, win_pct:0.0, playoffs:"Play-in", text:"Under construction - season-by-season highlights coming soon!",
        'playoff-matchups':{"Play-in": "L - COAST (4)"}},
    {'season':4, 'played':1, win_pct:0.8,playoffs:"Semifinals", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{"Play-in": "BYE",
            "First Round":"W - COAST (4)",
            "Semifinals":"L - CHEESE (6)"},
            'awards':{'Lemon':[], 'MVP':"Derek Stepan",
                     'All-stars':['Derek Stepan']}},
    {'season':5, 'played':1, win_pct:0.4, playoffs:"Play-in", text:"Under construction - season-by-season highlights coming soon!",
            'playoff-matchups':{"Play-in": "L - COAST (4)"}},
    {'season':6, 'played':1, win_pct:0.5, playoffs:"Semifinals", text:"Under construction - season-by-season highlights coming soon!",
            'playoff-matchups':{"Play-in": "W - CHECK (3)",
                                "First Round":"W - COAST (4)",
                                "Semifinals":"L - CHEESE (4)"},
            'awards':{}},
    {'season':7, 'played':1, win_pct:0.5, playoffs:"Play-in", text:"Under construction - season-by-season highlights coming soon!",
            'playoff-matchups':{"Play-in": "L - COAST (5)"}},
    {'season':8, 'played':1, win_pct:0.3, playoffs:"Play-in", text:"Under construction - season-by-season highlights coming soon!",
            'playoff-matchups':{"Play-in": "L - CHEESE (3)"},
            'awards':{'DPOTY':"Nick Schmaltz"}},
    {'season':9, 'played':1, win_pct:0.1, playoffs:"Missed", text:"Under construction - season-by-season highlights coming soon!",
        'playoff-matchups':{}}]





const irelandRecord = [
    {'season':1, 'played':0, win_pct:-1, playoffs:"Inactive", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{}},
    {'season':2, 'played':0, win_pct: -1, playoffs:"Inactive", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{}},
    {'season':3, 'played':0, win_pct:-1, playoffs:"Inactive", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{}},
    {'season':4, 'played':1, win_pct:0.6667,playoffs:"Inactive", text:"Under construction - season-by-season highlights coming soon!",
            'awards':{'All-stars':["M Murphy"]}},
    {'season':5, 'played':1, win_pct:0.4, playoffs:"Play-in", text:"Under construction - season-by-season highlights coming soon!",
            'playoff-matchups':{"Play-in": "L - RUSS (3)"}},
    {'season':6, 'played':1, win_pct:0.6, playoffs:"First Round", text:"Under construction - season-by-season highlights coming soon!",
            'playoff-matchups':{"Play-in": "W - BENCH (4)",
                                "First Round":"L - RUSS (3)"}},
    {'season':7, 'played':1, win_pct:0.5, playoffs:"Semifinals", text:"Under construction - season-by-season highlights coming soon!",
            'playoff-matchups':{"Play-in":"BYE",
                                "First Round":"W - CHEESE (3)",
                                "Semifinals":"L - TRAP (3)"},
            'awards':{'All-stars':["O O'Seylery"]}},
    {'season':8, 'played':1, win_pct:0.5, playoffs:"First Round", text:"Under construction - season-by-season highlights coming soon!",
        'playoff-matchups':{"Play-in": "BYE",
                                "First Round":"L - SHAME (4)"}},
    {'season':9, 'played':1, win_pct:0.4, playoffs:"First Round", text:"Under construction - season-by-season highlights coming soon!",
        'playoff-matchups':{"Play-in":"W - RUSS (3)",
                            "First Round":"L - SHAME (3)"},
        'awards':{'ROTY':"Lucky Charms"}}]



const montageMomentRecord = [
    {'season':1, 'played':0, win_pct:-1, playoffs:"Inactive", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{}},
    {'season':2, 'played':0, win_pct: -1, playoffs:"Inactive", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{}},
    {'season':3, 'played':0, win_pct:-1, playoffs:"Inactive", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{}},
    {'season':4, 'played':1, win_pct:0.4,playoffs:"Play-in", text:"Under construction - season-by-season highlights coming soon!",
                'playoff-matchups':{"Play-in": "L - TRAP (5)"},
            'awards':{'ROTY':"Takeapicofmika Withakodak",
            'All-stars':["T Withakodak"]}},
    {'season':5, 'played':1, win_pct:0.6, playoffs:"First Round", text:"Under construction - season-by-season highlights coming soon!",
            'playoff-matchups':{"Play-in": "BYE",
                                "First Round":"L - COAST (3)"},
            'awards':{'MVP':"Takeapicofmika Withakodak", 'All-stars':["T Withakodak"]}},
    {'season':6, 'played':1, win_pct:0.2, playoffs:"Missed", text:"c",
        'playoff-matchups':{},
        'awards':{'All-stars':["T Withakodak"]}},
    {'season':7, 'played':1, win_pct:0.5, playoffs:"First Round", text:"Under construction - season-by-season highlights coming soon!",
                'playoff-matchups':{"Play-in": "BYE",
                                "First Round":"L - TKL (3)"},
        'awards':{'All-stars':['T Withakodak']}},
    {'season':8, 'played':0, win_pct:-1, playoffs:"Inactive", text:"Under construction - season-by-season highlights coming soon!",
        'playoff-matchups':{}},
    {'season':9, 'played':0, win_pct:-1, playoffs:"Inactive", text:"Under construction - season-by-season highlights coming soon!",
        'playoff-matchups':{}}]

const petesRecord = [
    {'season':1, 'played':0, win_pct:-1, playoffs:"Inactive", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{}},
    {'season':2, 'played':0, win_pct: -1, playoffs:"Inactive", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{}},
    {'season':3, 'played':0, win_pct:-1, playoffs:"Inactive", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{}},
    {'season':4, 'played':0, win_pct:-1,playoffs:"Inactive", text:"Under construction - season-by-season highlights coming soon!"},
    {'season':5, 'played':0, win_pct:-1, playoffs:"Inactive", text:"Under construction - season-by-season highlights coming soon!"},
    {'season':6, 'played':0, win_pct:-1, playoffs:"Inactive", text:"Under construction - season-by-season highlights coming soon!"},
    {'season':7, 'played':0, win_pct:-1, playoffs:"Inactive", text:"Under construction - season-by-season highlights coming soon!"},
    {'season':8, 'played':1, win_pct:0.9, playoffs:"Champion", text:"Under construction - season-by-season highlights coming soon!",
        'playoff-matchups':{"Play-in":"L - TRAP (5)",
                            "First Round":"W - SHAME (3)",
                            "Semifinals":"W - TRAP (4)",
                            "Finals":"W - COAST (3)",
                            "Champion":"S8 CHAMPION"},
        'awards':{'Champion':[], "FMVP":"Pete Kodakpete", "Lemon":[], "MVP":"Pete Kodakpete",
            "GOTY":"Scott Darling", "ROTY":"Peter Cehlarik",
            "All-stars":["P Kodakpete", "P Darling", "P Pietrangelo"]}},
    {'season':9, 'played':1, win_pct:0.6, playoffs:"First Round", text:"Under construction - season-by-season highlights coming soon!",
        'playoff-matchups':{"Play-in":"BYE",
                            "First Round":"L - BENCH (3)"},
        'awards':{'All-stars':["P Holland", "P Ceresnak"]}}]


const pinguineRecord = [
    {'season':1, 'played':1, win_pct:0.5714, playoffs:"Finals", text:"The Pinguine tear through the playoffs and cruise easily to the finals in the league’s first season. General Manager Ben Artuso realizes he’s built far too overpowered a superteam and changes heart. Benching many of his key players during the finals series, he cedes victory in Game 7 to the Cheese (another team he manages—dw, it’s completely legal).",
    'playoff-matchups':{"Play-in": "L - SPAP (7)",
                        "First Round":"L - TKL (4)",
                        "Semifinals":"W - COAST (6)",
                        "Finals":"L - CHEESE (7)"},
        },
    {'season':2, 'played':1, win_pct: 0.3864, playoffs:"First Round", text:"Filled with remorse for building such a stacked and un-fun team, Artuso edits almost all of this players to make them worse in pretty much every way. The team sucks for a year and is removed from the league, never to appear again.",
    'playoff-matchups':{"Play-in": "BYE",
                        "First Round": "L - COAST (4)"}},
    {'season':3, 'played':0, win_pct:-1, playoffs:"Inactive", text:"",
    'playoff-matchups':{}},
    {'season':4, 'played':0, win_pct:-1,playoffs:"Inactive", text:""},
    {'season':5, 'played':0, win_pct:-1, playoffs:"Inactive", text:""},
    {'season':6, 'played':0, win_pct:-1, playoffs:"Inactive", text:""},
    {'season':7, 'played':0, win_pct:-1, playoffs:"Inactive", text:""},
    {'season':8, 'played':0, win_pct:-1, playoffs:"Inactive", text:"",
        'playoff-matchups':{}},
    {'season':9, 'played':0, win_pct:-1, playoffs:"Inactive", text:"",
        'playoff-matchups':{}}]


const russiansRecord = [
    {'season':1, 'played':1, win_pct:0.4, playoffs:"First Round", text:"The Russians stumble a bit in the league’s founding season, finishing with a losing season and first round playoff exit. As the crew begin to find their rhythm, it becomes clear to the fans that it’s all uphill from here. ",
    'playoff-matchups':{"Play-in": "W - LOOK (4)",
                        "First Round":"L - WOOD (6)"}},
    {'season':2, 'played':1, win_pct: 0.615, playoffs:"Semifinals", text:"Team captain Mikhaila Pobletov establishes herself as a rising star, winning her first 202HL MVP while leading her team to their first winning season and semifinals appearance.",
    'playoff-matchups':{"Play-in": "BYE",
                        "First Round": "W - TKL (5)",
                        "Semifinals":"L - R2L (4)"},
            'awards':{'MVP':'Mikhaila Pobletov', 'All-stars':['Mikhaila Pobletov', 'Nikita Kucherov']}},
    {'season':3, 'played':1, win_pct:0.769, playoffs:"Semifinals", text:"The Russians continue to climb, winning the regular season with a stunning 10-3 record. Continuing to develop her wicked backhand, Pobletov stuns the world by winning with the league’s first (and so far, only) back-to-back MVP. Despite her regular season dominance, another semifinals exit leads some to question her playoff mettle…",
    'playoff-matchups':{"Play-in": "BYE",
                        "First Round": "W - COAST (4)",
                        "Semifinals":"L - CHECK (4)"},
                'awards':{'Lemon':[], 'MVP':"Mikhaila Pobletov", 'All-stars':['Mikhaila Pobletov', 'Catherine the Great', 'Dmitry Orlov']}},
    {'season':4, 'played':1, win_pct:0.8,playoffs:"Champion", text:"Overwhelmed by the pressure, Pobletov abandons her countrymen to join the newly-formed Montage Moment. Stunningly, the team absolutely thrives in her absence, led by new captain (and finals MVP) Nikita Kucherov to their best-ever record and the franchise’s first championship.",
    'playoff-matchups': {"Play-in": "BYE",
            "First Round": "W - TRAP (4)",
            "Semifinals":"W - TKL (4)",
            "Finals":"W - CHEESE (4)",
            "Champion":"S4 CHAMPION"},
            'awards':{'Champion':[], 'FMVP':'Nikita Kucherov', 'Lemon':[], "GOTY":"Catherine The Great",
                    'All-stars':['Nikita Kucherov', 'Catherine The Great']}},
    {'season':5, 'played':1, win_pct:0.4, playoffs:"Finals", text:"Per league rules, the defending champion Russians are forced to sign the WGOAT (worst goalie of all time) Jaroslav Halak to a one-year deal. Management shrewdly acquires superstar Alexander Ovechkin to combat Halak’s miserable goaltending. Despite a pitiful regular season, Ovie leads them to a heartbreaking OT loss in Game 7 of the finals, the deepest ever playoff run by a defending champion.", 
        'playoff-matchups': {"Play-in": "BYE",
            "First Round": "W - IRE (3)",
            "Semifinals":"W - TRAP (4)",
            "Finals":"L - COAST (7)"},
        'All-stars':['Alexander Ovechkin']},
    {'season':6, 'played':1, win_pct:0.8, playoffs:"Champion", text:"THE TSARESS RETURNS. Hoping to be the difference-maker and finally win her chip, Mikhaila Pobletov returns to Russia on a one-year deal. She records a stunningly historic season, winning her THIRD league MVP and finally earning a ring as Finals MVP Alexander Ovechkin leads one of the most talented lineups ever to their second championship in three years.",
            'playoff-matchups': {"Play-in": "BYE",
            "First Round": "W - IRE (3)",
            "Semifinals":"W - SHAME (3)",
            "Finals":"W - CHEESE (3)",
            "Champion":"S6 CHAMPION"},
        'awards':{'Champion':[], 'FMVP':'Alexander Ovechkin', 'Lemon':[], 'MVP':"Mikhaila Pobletov",
                  'All-stars':['Mikhaila Pobletov', 'Something Dadonov','Something Zadorov']}},
    {'season':7, 'played':1, win_pct:0.5, playoffs:"First Round", text:"The dynasty was never meant to last. Aging superstars Pobletov, Ovechkin, Kucherov, and over 10 of their teammates retire en masse. The once unbeatable franchise is left with a crew of benchwarmers (and the long-dreaded return of Halak), but manages a .500 record and a single playoff series win. Even this will be short-lived, the only series they will win for the next 3 years.",
            'playoff-matchups':{'Play-in':"W - SPAP (4)",
                                "First Round":"L - SHAME (3)"}},
    {'season':8, 'played':1, win_pct:0.5, playoffs:"First Round", text:"More of the same. Halak is returned to the new champion Neutral Zone Trap, but the continued aging of remaining talent and overall mediocrity of new goaltender Semyon Varlamov take their toll. Another .500 record and another first-round exit for the dejected Russians.",
            'playoff-matchups':{"Play-in":"BYE",
                                "First Round":"L - TKL (3)"}},
    {'season':9, 'played':1, win_pct:0.6, playoffs:"Play-in", text:"It somehow gets worse! Despite notching 6 wins to finally record the first winning season since Season 6’s mass retirement, the motley crew are eliminated in the postseason’s play-in series for the first time in the team’s nine season history. ",
        'playoff-matchups':{"Play-in":"L - IRE (3)"}}]
const r2lRecord = [
    {'season':1, 'played':1, win_pct:0.474, playoffs:"First Round", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{"Play-in": "W - TRAP (7)",
                        "First Round":"L - COAST (4)"},
        'awards':{"MVP":"Mika Poblete", "All-stars":['Mika Poblete']}},
    {'season':2, 'played':1, win_pct: 0.846, playoffs:"Finals", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{"Play-in": "BYE",
                        "First Round": "W - SCOUT (7)",
                        "Semifinals":"W - RUSS (4)",
                        "Finals":"L - LOOK (4)"},
        'awards':{"All-stars":["Mika Poblete", "Henrik Lundqvist"]}},
    {'season':3, 'played':1, win_pct:0.615, playoffs:"Semifinals", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{"Play-in": "BYE",
                        "First Round": "W - TRAP (7)",
                        "Semifinals":"L - SCOUT (4)"},
            'awards':{"All-stars":["Megan Marshall"]}},
    {'season':4, 'played':1, win_pct:0.636,playoffs:"First Round", text:"Under construction - season-by-season highlights coming soon!",
        'playoff-matchups':{"Play-in":"BYE",
                            "First Round":"L - TKL (4)"},
        'awards':{'All-stars':["T Hickey", 'J Frk']}},
    {'season':5, 'played':1, win_pct:0.3, playoffs:"Missed", text:"Under construction - season-by-season highlights coming soon!",
        'playoff-matchups':{}},
    {'season':6, 'played':0, win_pct:-1, playoffs:"Inactive", text:"Under construction - season-by-season highlights coming soon!"},
    {'season':7, 'played':0, win_pct:-1, playoffs:"Inactive", text:"Under construction - season-by-season highlights coming soon!"},
    {'season':8, 'played':0, win_pct:-1, playoffs:"Inactive", text:"Under construction - season-by-season highlights coming soon!",
        'playoff-matchups':{}},
    {'season':9, 'played':0, win_pct:-1, playoffs:"Inactive", text:"Under construction - season-by-season highlights coming soon!",
        'playoff-matchups':{}}]




const scoutersRecord = [
    {'season':1, 'played':1, win_pct:0.5, playoffs:"Play-in", text:"One of the league's founding teams, the Scouters make their 202HL debut with a pedestrain 5-5 record and an embarassing loss in the play-in round of the league's first postseason tournament.",
    'playoff-matchups':{"Play-in": "L - SPAP (7)"}},
    {'season':2, 'played':1, win_pct: 0.83, playoffs:"First Round", text:"While their regular season performance falls to a miserable 3-10 record, the Scouters pick up their first playoff win in Season 2's play-in series...only to be unceremoniously bounced in the first round.",
    'playoff-matchups':{"Play-in": "W - SPAP (5)",
                        "First Round": "L - R2L (7)"}},
    {'season':3, 'played':1, win_pct:0.24, playoffs:"Finals", text:"Sick of the incompetent management of Nich Seyler, the Scouters players' union forces a sale to Steel City under the new management of Ben Artuso. With the shrewd aquisition of free agent Miscore Goalete, they improve to an 8-5 regular season and suffer a heartbreaking OT loss in Game 7 of the league championship.",
    'playoff-matchups':{"Play-in": "BYE",
                        "First Round": "W - TKL (6)",
                        "Semifinals":"W - R2L (4)",
                        "Finals":"L - SCOUT (7)"},
            'awards':{"GOTY":"Mike Condon", "ROTY":"Miscore Goalete", "All-stars":['Mike Condon', "Miscore Goalete"]}},
    {'season':4, 'played':0, win_pct:-1,playoffs:"Inactive", text:"Stunned by their embarassing Season 3 loss, owner and general manager Ben Artuso places the Scouters on an indefinite suspension."},
    {'season':5, 'played':0, win_pct:-1, playoffs:"Inactive", text:"b"},
    {'season':6, 'played':0, win_pct:-1, playoffs:"Inactive", text:"c"},
    {'season':7, 'played':1, win_pct:0.4, playoffs:"Missed", text:"d"},
    {'season':8, 'played':1, win_pct:0.3, playoffs:"Play-in", text:"",
        'playoff-matchups':{"Play-in":"L - TRAP (5)"},
        'awards':{'All-stars':['Klim Kostin']}},
    {'season':9, 'played':1, win_pct:0.3, playoffs:"First Round", text:"f",
        'playoff-matchups':{"Play-in":"W - CHEESE (3)",
                            "First Round":"L - TKL (3)"},
        'awards':{'COTY':"Nich Seyler"}}]
    
const shameKnightsRecord = [
    {'season':1, 'played':0, win_pct:-1, playoffs:"Inactive", text:"",
    'playoff-matchups':{}},
    {'season':2, 'played':0, win_pct: -1, playoffs:"Inactive", text:"",
    'playoff-matchups':{}},
    {'season':3, 'played':0, win_pct:-1, playoffs:"Inactive", text:"",
    'playoff-matchups':{}},
    {'season':4, 'played':0, win_pct:-1,playoffs:"Inactive", text:""},
    {'season':5, 'played':0, win_pct:-1, playoffs:"Inactive", text:""},
    {'season':6, 'played':1, win_pct:0.4, playoffs:"Semifinals", text:"Under construction - season-by-season highlights coming soon!",
        'playoff-matchups':{
                'Play-in':"BYE",
                "First Round":"W - TRAP (4)",
                "Semifinals":"L - RUSS (3)"
        },
        'awards':{'ROTY':"Kole Sherwood", "All-stars":[]}},
    {'season':7, 'played':1, win_pct:0.7, playoffs:"Semifinals", text:"Under construction - season-by-season highlights coming soon!",
        'playoff-matchups':{
            'Play-in':"BYE",
            "First Round":"W - RUSS (3)",
            "Semifinals":"L - TKL (5)"
    }, 'awards':{'MIPOTY':'Ryan Spooner', "All-stars":["Ryan Spooner", "D Nurse"]}},
    {'season':8, 'played':1, win_pct:0.8, playoffs:"Semifinals", text:"Under construction - season-by-season highlights coming soon!",
          'playoff-matchups':{
                'Play-in':"BYE",
                "First Round":"W - IRE (4)",
                "Semifinals":"L - COAST (3)"
        }, 'awards':{"GOTY":"Scott Darling", "All-stars":["S Darling", "J Skinner", "W Baptiste", "D Nurse"]}},
    {'season':9, 'played':1, win_pct:0.7, playoffs:"Champion", text:"Under construction - season-by-season highlights coming soon!",
        'playoff-matchups':{"Play-in":"BYE",
                            "First Round":"W - IRE (3)",
                            "Semifinals":"W - TRAP (4)",
                            "Finals":"W - BENCH (3)",
                            "Champion":"S9 CHAMPION"},
        'awards':{"Champion":[], 'FMVP':"Nowyur Kareerisova", 'Lemon':[],
        'DPOTY':"Will Butcher",
        'All-stars':["W Butcher", "Kole Sherwood", "J Skinner"]}}]




const spappersRecord = [
    {'season':1, 'played':1, win_pct:0.09, playoffs:"First Round", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{"Play-in": "W - SCOUT (7)",
                        "First Round":"L - CHEESE (7)"}},
    {'season':2, 'played':1, win_pct: 0.307, playoffs:"Play-in", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{"Play-in": "L - SCOUT (5)"},
        'awards':{'COTY':"Carson Lambert", "All-stars":["J Toji"]}},
    {'season':3, 'played':1, win_pct:0.461, playoffs:"Play-in", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{"Play-in": "L - TKL (5)"},
        'awards':{'All-stars':["J Toji"]}},
    {'season':4, 'played':1, win_pct:0.0,playoffs:"Missed", text:"Under construction - season-by-season highlights coming soon!"},
    {'season':5, 'played':1, win_pct:0.2, playoffs:"Missed", text:"Under construction - season-by-season highlights coming soon!",
        'awards':{'COTY':"Carson Lambert"}},
    {'season':6, 'played':1, win_pct:0.3, playoffs:"Missed", text:"Under construction - season-by-season highlights coming soon!",
        'awards':{'COTY':"Carson Lambert"}},
    {'season':7, 'played':1, win_pct:0.2, playoffs:"Play-in", text:"Under construction - season-by-season highlights coming soon!",
            'playoff-matchups':{"Play-in":"L - RUSS (4)"},
        'awards':{'COTY':"Carson Lambert", "All-stars":['H Ecker']}},
    {'season':8, 'played':1, win_pct:0.3, playoffs:"Missed", text:"Under construction - season-by-season highlights coming soon!",
        'playoff-matchups':{},
        'awards':{'COTY':"Carson Lambert"}},
    {'season':9, 'played':1, win_pct:0.0, playoffs:"Missed", text:"Under construction - season-by-season highlights coming soon!",
        'playoff-matchups':{},}]

const tacoTimeRecord = [
    {'season':1, 'played':1, win_pct:0.625, playoffs:"First Round", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{"Play-in": "BYE",
                        "First Round":"L - PING (4)"}},
    {'season':2, 'played':1, win_pct: 0.538, playoffs:"First Round", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{"Play-in": "BYE",
                        "First Round": "L - RUSS (5)"},
    'awards':{'DPOTY':'Andreas Borgman', "All-stars":["Andreas Borgman", "Pierre Engvall"]}},
    {'season':3, 'played':1, win_pct:0.4615, playoffs:"First Round", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{"Play-in": "W - SPAP (5)",
                        "First Round": "L - SCOUT (6)"},
    'awards':{'All-stars':['Andreas Borgman']}},
    {'season':4, 'played':1, win_pct:0.6,playoffs:"Semifinals", text:"Under construction - season-by-season highlights coming soon!",
                    'playoff-matchups':{"Play-in":"BYE",
                                "First Round":"W - R2L (4)",
                                "Semifinals":"L - RUSS (4)"},
                    'awards':{'DPOTY':"Josh Jooris",
                        'All-stars':['J Jooris', 'M Marincin']}},
    {'season':5, 'played':1, win_pct:0.5, playoffs:"First Round", text:"Under construction - season-by-season highlights coming soon!",
                'playoff-matchups':{"Play-in":"BYE",
                            "First Round":"L - BENCH (5)"},
                'awards':{'All-stars':['J Jooris', 'C Knobbert']}},
    {'season':6, 'played':1, win_pct:0.6, playoffs:"First Round", text:"Under construction - season-by-season highlights coming soon!",
        'playoff-matchups':{"Play-in":"BYE",
                            "First Round":"L - CHEESE (4)"},
        'awards':{'DPOTY':'Richard Butkus', 'GOTY':"Michael Hutchinson",
                'All-stars':["R Butkus", 'M Hutchinson', "C Knobbert" ]}},
    {'season':7, 'played':1, win_pct:0.5, playoffs:"Finals", text:"Under construction - season-by-season highlights coming soon!",
            'playoff-matchups':{"Play-in":"BYE",
                            "First Round":"W - MONT (3)",
                            "Semifinals":"W - SHAME (5)",
                            "Finals":"L - TRAP (5)"},
            'awards':{'GOTY':"Michael Hutchinson",
            'All-stars':['M Hutchinson', 'Andreas Borgman']}},
    {'season':8, 'played':1, win_pct:0.7, playoffs:"Semifinals", text:"Under construction - season-by-season highlights coming soon!",
        'playoff-matchups':{"Play-in":"BYE",
                            "First Round":"L - RUSS (3)",
                            "Semifinals":"L - PETE (4)"},
        'awards':{'MIPOTY':'Jeremy Bracco',
                'All-stars':[]}},
    {'season':9, 'played':1, win_pct:0.7, playoffs:"Semifinals", text:"fUnder construction - season-by-season highlights coming soon!",
        'playoff-matchups':{"Play-in":"BYE",
                            "First Round":"W - SCOUT (5)",
                            "Semifinals":"L - BENCH (5)"},
        'awards':{'Lemon':[]}}]

const trapRecord  = [
    {'season':1, 'played':1, win_pct:0.34782, playoffs:"Play-in", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{"Play-in": "L - R2L (4)"}},
    {'season':2, 'played':1, win_pct: 0.3077, playoffs:"Play-in", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{"Play-in": "L - CHEESE (4)"},
        'awards':{'All-stars':['Alex Pietrangelo']}},
    {'season':3, 'played':1, win_pct:0.5384, playoffs:"First Round", text:"Under construction - season-by-season highlights coming soon!",
    'playoff-matchups':{"Play-in": "BYE",
                        "First Round": "L - R2L (7)"
                        },
    'awards':{'MIPOTY':'Elvis Merzlikens'}},
    {'season':4, 'played':1, win_pct:0.4,playoffs:"First Round", text:"Under construction - season-by-season highlights coming soon!",
                'playoff-matchups':{"Play-in": "W - MONT (5)",
                        "First Round": "L - RUSS (4)"
                        }},
    {'season':5, 'played':1, win_pct:0.6, playoffs:"Semifinals", text:"Under construction - season-by-season highlights coming soon!",
            'playoff-matchups':{"Play-in": "BYE",
                        "First Round": "W - CHECK (4)",
                        "Semifinals":"L - RUSS (4)"
                        }},
    {'season':6, 'played':1, win_pct:0.4, playoffs:"First Round", text:"Under construction - season-by-season highlights coming soon!",
            'playoff-matchups':{"Play-in": "BYE",
                        "First Round": "L - SHAME (4)"
                        }},
    {'season':7, 'played':1, win_pct:0.9, playoffs:"Champion", text:"Under construction - season-by-season highlights coming soon!",
                'playoff-matchups':{"Play-in": "BYE",
                        "First Round": "W - COAST (4)",
                        "Semifinals":"W - IRE (3)",
                        "Finals":"W - TKL (5)",
                        "Champion":"S7 CHAMPION"
                        },
                'awards':{'Champion':{}, 'FMVP':"Johnny Toji", 'Lemon':{}, 'MVP':'Johnny Toji', 
                          'All-stars':['Name Parayko', 'Name Tarasenko', 'Name Toji']}},
    {'season':8, 'played':1, win_pct:0.4, playoffs:"First Round", text:"Under construction - season-by-season highlights coming soon!",
        'playoff-matchups':{"Play-in":"W - SCOUT (5)",
                            "First Round":"L - PETE (4)"}},
    {'season':9, 'played':1, win_pct:0.7, playoffs:"Semifinals", text:"Under construction - season-by-season highlights coming soon!",
        'playoff-matchups':{"Play-in":"BYE",
                            "First Round":"W - COAST (3)",
                            "Semifinals":"L - SHAME (4)"},
        'awards':{'MIPOTY':"Zemgus Girgensons"}}]

