var benchminorsPlayers = [
    {
      "star": "AMOROSA",
      "star_goals": 1.0,
      "star_assists": 6.0,
      "star_hits": 9.0,
      "season_number": 17,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 4.0,
      "points_in_game": 4.0,
      "bruiser": 1.3
    },
    {
      "star": "CHATHAM",
      "star_goals": 4.0,
      "star_assists": 2.0,
      "star_hits": 1.0,
      "season_number": 10,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.2
    },
    {
      "star": "DAHL",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 5,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "DODERO",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 9,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "DUBOIS",
      "star_goals": 30.0,
      "star_assists": 21.0,
      "star_hits": 29.0,
      "season_number": 111,
      "points": 51.0,
      "hat_trick": 4,
      "goals_in_game": 3.0,
      "assists_in_game": 3.0,
      "points_in_game": 6.0,
      "bruiser": 0.6
    },
    {
      "star": "FLEURY",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 5,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 0.0
    },
    {
      "star": "GAUDREAU",
      "star_goals": 31.0,
      "star_assists": 24.0,
      "star_hits": 17.0,
      "season_number": 129,
      "points": 55.0,
      "hat_trick": 2,
      "goals_in_game": 3.0,
      "assists_in_game": 5.0,
      "points_in_game": 6.0,
      "bruiser": 0.3
    },
    {
      "star": "KANZIG",
      "star_goals": 1.0,
      "star_assists": 4.0,
      "star_hits": 3.0,
      "season_number": 15,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 3.0,
      "bruiser": 0.6
    },
    {
      "star": "KESSY",
      "star_goals": 3.0,
      "star_assists": 3.0,
      "star_hits": 0.0,
      "season_number": 11,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "LAMBERTS",
      "star_goals": 4.0,
      "star_assists": 4.0,
      "star_hits": 1.0,
      "season_number": 25,
      "points": 8.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.1
    },
    {
      "star": "LEMIEUX",
      "star_goals": 1.0,
      "star_assists": 9.0,
      "star_hits": 7.0,
      "season_number": 12,
      "points": 10.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 6.0,
      "points_in_game": 6.0,
      "bruiser": 0.7
    },
    {
      "star": "LEWIS",
      "star_goals": 3.0,
      "star_assists": 4.0,
      "star_hits": 6.0,
      "season_number": 25,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.9
    },
    {
      "star": "MANGIAPANE",
      "star_goals": 9.0,
      "star_assists": 6.0,
      "star_hits": 7.0,
      "season_number": 46,
      "points": 15.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.5
    },
    {
      "star": "MAROSZ",
      "star_goals": 5.0,
      "star_assists": 2.0,
      "star_hits": 2.0,
      "season_number": 25,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.3
    },
    {
      "star": "MOROZ",
      "star_goals": 24.0,
      "star_assists": 5.0,
      "star_hits": 13.0,
      "season_number": 75,
      "points": 29.0,
      "hat_trick": 5,
      "goals_in_game": 4.0,
      "assists_in_game": 2.0,
      "points_in_game": 5.0,
      "bruiser": 0.4
    },
    {
      "star": "PETRYK",
      "star_goals": 10.0,
      "star_assists": 18.0,
      "star_hits": 7.0,
      "season_number": 51,
      "points": 28.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 5.0,
      "points_in_game": 6.0,
      "bruiser": 0.2
    },
    {
      "star": "SCHEMPP",
      "star_goals": 2.0,
      "star_assists": 3.0,
      "star_hits": 3.0,
      "season_number": 23,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 3.0,
      "bruiser": 0.6
    },
    {
      "star": "THEODORE",
      "star_goals": 3.0,
      "star_assists": 3.0,
      "star_hits": 4.0,
      "season_number": 11,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.7
    },
    {
      "star": "VALA",
      "star_goals": 5.0,
      "star_assists": 7.0,
      "star_hits": 7.0,
      "season_number": 37,
      "points": 12.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 3.0,
      "bruiser": 0.6
    },
    {
      "star": "WHITE",
      "star_goals": 2.0,
      "star_assists": 2.0,
      "star_hits": 3.0,
      "season_number": 13,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.8
    }
  ];

var benchminorsSeason = [
    {
      "star": "AMOROSA (S8)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 4.0,
      "season_number": 8,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 1.3
    },
    {
      "star": "AMOROSA (S9)",
      "star_goals": 0.0,
      "star_assists": 4.0,
      "star_hits": 5.0,
      "season_number": 9,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 0.0,
      "assists_in_game": 4.0,
      "points_in_game": 4.0,
      "bruiser": 1.2
    },
    {
      "star": "CHATHAM (S5)",
      "star_goals": 4.0,
      "star_assists": 2.0,
      "star_hits": 1.0,
      "season_number": 10,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.2
    },
    {
      "star": "DAHL (S5)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 5,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "DODERO (S9)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 9,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "DUBOIS (S5)",
      "star_goals": 16.0,
      "star_assists": 10.0,
      "star_hits": 12.0,
      "season_number": 40,
      "points": 26.0,
      "hat_trick": 3,
      "goals_in_game": 3.0,
      "assists_in_game": 3.0,
      "points_in_game": 6.0,
      "bruiser": 0.5
    },
    {
      "star": "DUBOIS (S6)",
      "star_goals": 3.0,
      "star_assists": 1.0,
      "star_hits": 4.0,
      "season_number": 12,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.0
    },
    {
      "star": "DUBOIS (S7)",
      "star_goals": 4.0,
      "star_assists": 2.0,
      "star_hits": 4.0,
      "season_number": 14,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.7
    },
    {
      "star": "DUBOIS (S9)",
      "star_goals": 7.0,
      "star_assists": 8.0,
      "star_hits": 9.0,
      "season_number": 45,
      "points": 15.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 3.0,
      "points_in_game": 5.0,
      "bruiser": 0.6
    },
    {
      "star": "FLEURY (S5)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 5,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 0.0
    },
    {
      "star": "GADREAU (S5)",
      "star_goals": 2.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 5,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.0
    },
    {
      "star": "GAUDREAU (S5)",
      "star_goals": 4.0,
      "star_assists": 6.0,
      "star_hits": 3.0,
      "season_number": 15,
      "points": 10.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 4.0,
      "points_in_game": 5.0,
      "bruiser": 0.3
    },
    {
      "star": "GAUDREAU (S6)",
      "star_goals": 11.0,
      "star_assists": 3.0,
      "star_hits": 6.0,
      "season_number": 30,
      "points": 14.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.4
    },
    {
      "star": "GAUDREAU (S7)",
      "star_goals": 5.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 14,
      "points": 6.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "GAUDREAU (S8)",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 1.0,
      "season_number": 16,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.2
    },
    {
      "star": "GAUDREAU (S9)",
      "star_goals": 8.0,
      "star_assists": 12.0,
      "star_hits": 7.0,
      "season_number": 54,
      "points": 20.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 5.0,
      "points_in_game": 6.0,
      "bruiser": 0.3
    },
    {
      "star": "KANZIG (S6)",
      "star_goals": 0.0,
      "star_assists": 3.0,
      "star_hits": 0.0,
      "season_number": 6,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 0.0,
      "assists_in_game": 3.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "KANZIG (S9)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 3.0,
      "season_number": 9,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.5
    },
    {
      "star": "KESSY (S4)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 4,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "KESSY (S7)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 7,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "LAMBERTS (S7)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 7,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "LAMBERTS (S9)",
      "star_goals": 3.0,
      "star_assists": 3.0,
      "star_hits": 1.0,
      "season_number": 18,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.2
    },
    {
      "star": "LEMIEUX (S6)",
      "star_goals": 1.0,
      "star_assists": 9.0,
      "star_hits": 7.0,
      "season_number": 12,
      "points": 10.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 6.0,
      "points_in_game": 6.0,
      "bruiser": 0.7
    },
    {
      "star": "LEWIS (S7)",
      "star_goals": 1.0,
      "star_assists": 3.0,
      "star_hits": 0.0,
      "season_number": 7,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.0
    },
    {
      "star": "LEWIS (S9)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 6.0,
      "season_number": 18,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 2.0
    },
    {
      "star": "MANGIAPANE (S5)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 1.0,
      "season_number": 5,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.5
    },
    {
      "star": "MANGIAPANE (S6)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 2.0,
      "season_number": 6,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.7
    },
    {
      "star": "MANGIAPANE (S8)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 2.0,
      "season_number": 8,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 1.0
    },
    {
      "star": "MANGIAPANE (S9)",
      "star_goals": 5.0,
      "star_assists": 3.0,
      "star_hits": 2.0,
      "season_number": 27,
      "points": 8.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.2
    },
    {
      "star": "MAROSZ (S8)",
      "star_goals": 4.0,
      "star_assists": 1.0,
      "star_hits": 2.0,
      "season_number": 16,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.4
    },
    {
      "star": "MAROSZ (S9)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 9,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "MOROZ (S5)",
      "star_goals": 4.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 10,
      "points": 4.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 0.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "MOROZ (S6)",
      "star_goals": 3.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 6,
      "points": 3.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 0.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "MOROZ (S7)",
      "star_goals": 5.0,
      "star_assists": 2.0,
      "star_hits": 2.0,
      "season_number": 14,
      "points": 7.0,
      "hat_trick": 1,
      "goals_in_game": 4.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.3
    },
    {
      "star": "MOROZ (S9)",
      "star_goals": 12.0,
      "star_assists": 3.0,
      "star_hits": 11.0,
      "season_number": 45,
      "points": 15.0,
      "hat_trick": 2,
      "goals_in_game": 4.0,
      "assists_in_game": 1.0,
      "points_in_game": 5.0,
      "bruiser": 0.7
    },
    {
      "star": "PETRYK (S4)",
      "star_goals": 2.0,
      "star_assists": 6.0,
      "star_hits": 2.0,
      "season_number": 8,
      "points": 8.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 5.0,
      "points_in_game": 6.0,
      "bruiser": 0.2
    },
    {
      "star": "PETRYK (S5)",
      "star_goals": 4.0,
      "star_assists": 1.0,
      "star_hits": 1.0,
      "season_number": 10,
      "points": 5.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.2
    },
    {
      "star": "PETRYK (S6)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 6,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "PETRYK (S9)",
      "star_goals": 3.0,
      "star_assists": 9.0,
      "star_hits": 4.0,
      "season_number": 27,
      "points": 12.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 4.0,
      "points_in_game": 5.0,
      "bruiser": 0.3
    },
    {
      "star": "SCHEMPP (S5)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 2.0,
      "season_number": 5,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 2.0
    },
    {
      "star": "SCHEMPP (S9)",
      "star_goals": 1.0,
      "star_assists": 3.0,
      "star_hits": 1.0,
      "season_number": 18,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 3.0,
      "bruiser": 0.2
    },
    {
      "star": "THEODORE (S5)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 2.0,
      "season_number": 5,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.7
    },
    {
      "star": "THEODORE (S6)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 2.0,
      "season_number": 6,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.7
    },
    {
      "star": "VALA (S6)",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 12,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "VALA (S7)",
      "star_goals": 0.0,
      "star_assists": 3.0,
      "star_hits": 4.0,
      "season_number": 7,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 0.0,
      "assists_in_game": 3.0,
      "points_in_game": 3.0,
      "bruiser": 1.3
    },
    {
      "star": "VALA (S9)",
      "star_goals": 2.0,
      "star_assists": 2.0,
      "star_hits": 3.0,
      "season_number": 18,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.8
    },
    {
      "star": "WHITE (S4)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 2.0,
      "season_number": 4,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.0
    },
    {
      "star": "WHITE (S9)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 1.0,
      "season_number": 9,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.5
    }
  ];