var checkersPlayers = [
    {
      "star": "AUBE-KUBEL",
      "star_goals": 17.0,
      "star_assists": 20.0,
      "star_hits": 50.0,
      "season_number": 48,
      "points": 37.0,
      "hat_trick": 1,
      "goals_in_game": 4.0,
      "assists_in_game": 3.0,
      "points_in_game": 5.0,
      "bruiser": 1.4
    },
    {
      "star": "BELLOWS",
      "star_goals": 7.0,
      "star_assists": 2.0,
      "star_hits": 10.0,
      "season_number": 14,
      "points": 9.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 1.1
    },
    {
      "star": "BLIDH",
      "star_goals": 2.0,
      "star_assists": 2.0,
      "star_hits": 5.0,
      "season_number": 9,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.2
    },
    {
      "star": "BUNTING",
      "star_goals": 10.0,
      "star_assists": 2.0,
      "star_hits": 21.0,
      "season_number": 19,
      "points": 12.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 1.8
    },
    {
      "star": "CAAMANO",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 3.0,
      "season_number": 6,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.5
    },
    {
      "star": "CLENDENING",
      "star_goals": 8.0,
      "star_assists": 14.0,
      "star_hits": 71.0,
      "season_number": 29,
      "points": 22.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 5.0,
      "bruiser": 3.2
    },
    {
      "star": "CLENDENNING",
      "star_goals": 1.0,
      "star_assists": 5.0,
      "star_hits": 28.0,
      "season_number": 18,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 3.0,
      "bruiser": 4.7
    },
    {
      "star": "CRAMAROSSA",
      "star_goals": 7.0,
      "star_assists": 2.0,
      "star_hits": 19.0,
      "season_number": 20,
      "points": 9.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 2.1
    },
    {
      "star": "FRANKO",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 4,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "GALLANT",
      "star_goals": 6.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 10,
      "points": 8.0,
      "hat_trick": 1,
      "goals_in_game": 5.0,
      "assists_in_game": 1.0,
      "points_in_game": 6.0,
      "bruiser": 0.0
    },
    {
      "star": "GERBE",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 4.0,
      "season_number": 3,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 4.0
    },
    {
      "star": "IMAMA",
      "star_goals": 3.0,
      "star_assists": 5.0,
      "star_hits": 3.0,
      "season_number": 10,
      "points": 8.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 4.0,
      "points_in_game": 5.0,
      "bruiser": 0.4
    },
    {
      "star": "KOSTIN",
      "star_goals": 33.0,
      "star_assists": 29.0,
      "star_hits": 76.0,
      "season_number": 78,
      "points": 62.0,
      "hat_trick": 4,
      "goals_in_game": 4.0,
      "assists_in_game": 4.0,
      "points_in_game": 5.0,
      "bruiser": 1.2
    },
    {
      "star": "LAFFERTY",
      "star_goals": 4.0,
      "star_assists": 0.0,
      "star_hits": 11.0,
      "season_number": 10,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 2.8
    },
    {
      "star": "REDDEKOP",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 9.0,
      "season_number": 5,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 9.0
    },
    {
      "star": "REDDEKOPP",
      "star_goals": 4.0,
      "star_assists": 3.0,
      "star_hits": 20.0,
      "season_number": 17,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 2.9
    },
    {
      "star": "SEILOFF",
      "star_goals": 3.0,
      "star_assists": 1.0,
      "star_hits": 14.0,
      "season_number": 9,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 3.5
    },
    {
      "star": "SMITH",
      "star_goals": 5.0,
      "star_assists": 1.0,
      "star_hits": 10.0,
      "season_number": 18,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.7
    },
    {
      "star": "ST. DENIS",
      "star_goals": 8.0,
      "star_assists": 10.0,
      "star_hits": 25.0,
      "season_number": 22,
      "points": 18.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 1.4
    },
    {
      "star": "TINORDI",
      "star_goals": 10.0,
      "star_assists": 7.0,
      "star_hits": 94.0,
      "season_number": 38,
      "points": 17.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 5.5
    },
    {
      "star": "TINORI",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 11.0,
      "season_number": 3,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 11.0
    }
  ];

var checkersSeason = [
    {
      "star": "AUBE-KUBEL (S3)",
      "star_goals": 9.0,
      "star_assists": 14.0,
      "star_hits": 30.0,
      "season_number": 27,
      "points": 23.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 3.0,
      "bruiser": 1.3
    },
    {
      "star": "AUBE-KUBEL (S5)",
      "star_goals": 6.0,
      "star_assists": 5.0,
      "star_hits": 8.0,
      "season_number": 15,
      "points": 11.0,
      "hat_trick": 1,
      "goals_in_game": 4.0,
      "assists_in_game": 3.0,
      "points_in_game": 5.0,
      "bruiser": 0.7
    },
    {
      "star": "AUBE-KUBEL (S6)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 12.0,
      "season_number": 6,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 4.0
    },
    {
      "star": "BELLOWS (S3)",
      "star_goals": 6.0,
      "star_assists": 2.0,
      "star_hits": 7.0,
      "season_number": 9,
      "points": 8.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.9
    },
    {
      "star": "BELLOWS (S5)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 3.0,
      "season_number": 5,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 3.0
    },
    {
      "star": "BLIDH (S3)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 2.0,
      "season_number": 3,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.0
    },
    {
      "star": "BLIDH (S6)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 3.0,
      "season_number": 6,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.5
    },
    {
      "star": "BUNTING (S3)",
      "star_goals": 7.0,
      "star_assists": 2.0,
      "star_hits": 19.0,
      "season_number": 15,
      "points": 9.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 2.0,
      "bruiser": 2.1
    },
    {
      "star": "BUNTING (S4)",
      "star_goals": 3.0,
      "star_assists": 0.0,
      "star_hits": 2.0,
      "season_number": 4,
      "points": 3.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 0.0,
      "points_in_game": 3.0,
      "bruiser": 0.7
    },
    {
      "star": "CAAMANO (S6)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 3.0,
      "season_number": 6,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.5
    },
    {
      "star": "CLENDENING (S3)",
      "star_goals": 4.0,
      "star_assists": 8.0,
      "star_hits": 32.0,
      "season_number": 15,
      "points": 12.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 2.7
    },
    {
      "star": "CLENDENING (S4)",
      "star_goals": 2.0,
      "star_assists": 3.0,
      "star_hits": 14.0,
      "season_number": 4,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 5.0,
      "bruiser": 2.8
    },
    {
      "star": "CLENDENING (S5)",
      "star_goals": 2.0,
      "star_assists": 3.0,
      "star_hits": 25.0,
      "season_number": 10,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 3.0,
      "bruiser": 5.0
    },
    {
      "star": "CLENDENNING (S6)",
      "star_goals": 1.0,
      "star_assists": 5.0,
      "star_hits": 28.0,
      "season_number": 18,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 3.0,
      "bruiser": 4.7
    },
    {
      "star": "CRAMAROSSA (S3)",
      "star_goals": 5.0,
      "star_assists": 1.0,
      "star_hits": 7.0,
      "season_number": 9,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.2
    },
    {
      "star": "CRAMAROSSA (S5)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 7.0,
      "season_number": 5,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 3.5
    },
    {
      "star": "CRAMAROSSA (S6)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 5.0,
      "season_number": 6,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 5.0
    },
    {
      "star": "FRANKO (S4)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 4,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "GALLANT (S4)",
      "star_goals": 5.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 4,
      "points": 6.0,
      "hat_trick": 1,
      "goals_in_game": 5.0,
      "assists_in_game": 1.0,
      "points_in_game": 6.0,
      "bruiser": 0.0
    },
    {
      "star": "GALLANT (S6)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 6,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "GERBE (S3)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 4.0,
      "season_number": 3,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 4.0
    },

    {
      "star": "IMAMA (S3)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 1.0,
      "season_number": 6,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.3
    },
    {
      "star": "IMAMA (S4)",
      "star_goals": 1.0,
      "star_assists": 4.0,
      "star_hits": 2.0,
      "season_number": 4,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 4.0,
      "points_in_game": 5.0,
      "bruiser": 0.4
    },
    {
      "star": "KOSTIN (S3)",
      "star_goals": 11.0,
      "star_assists": 17.0,
      "star_hits": 30.0,
      "season_number": 27,
      "points": 28.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 4.0,
      "points_in_game": 5.0,
      "bruiser": 1.1
    },
    {
      "star": "KOSTIN (S4)",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 5.0,
      "season_number": 8,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 1.0
    },
    {
      "star": "KOSTIN (S5)",
      "star_goals": 14.0,
      "star_assists": 6.0,
      "star_hits": 22.0,
      "season_number": 25,
      "points": 20.0,
      "hat_trick": 3,
      "goals_in_game": 4.0,
      "assists_in_game": 2.0,
      "points_in_game": 5.0,
      "bruiser": 1.1
    },
    {
      "star": "KOSTIN (S6)",
      "star_goals": 5.0,
      "star_assists": 4.0,
      "star_hits": 19.0,
      "season_number": 18,
      "points": 9.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 2.1
    },
    {
      "star": "LAFFERTY (S5)",
      "star_goals": 4.0,
      "star_assists": 0.0,
      "star_hits": 11.0,
      "season_number": 10,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 2.8
    },
    {
      "star": "REDDEKOP (S5)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 9.0,
      "season_number": 5,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 9.0
    },
    {
      "star": "REDDEKOPP (S3)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 7.0,
      "season_number": 6,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 2.3
    },
    {
      "star": "REDDEKOPP (S5)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 3.0,
      "season_number": 5,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.5
    },
    {
      "star": "REDDEKOPP (S6)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 10.0,
      "season_number": 6,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 5.0
    },
    {
      "star": "SEILOFF (S4)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 9.0,
      "season_number": 4,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 3.0
    },
    {
      "star": "SEILOFF (S5)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 5.0,
      "season_number": 5,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 5.0
    },
    {
      "star": "SMITH (S3)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 7.0,
      "season_number": 6,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 2.3
    },
    {
      "star": "SMITH (S6)",
      "star_goals": 3.0,
      "star_assists": 0.0,
      "star_hits": 3.0,
      "season_number": 12,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 1.0
    },
    {
      "star": "ST. DENIS (S3)",
      "star_goals": 8.0,
      "star_assists": 4.0,
      "star_hits": 15.0,
      "season_number": 12,
      "points": 12.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 1.2
    },
    {
      "star": "ST. DENIS (S5)",
      "star_goals": 0.0,
      "star_assists": 6.0,
      "star_hits": 10.0,
      "season_number": 10,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 0.0,
      "assists_in_game": 3.0,
      "points_in_game": 3.0,
      "bruiser": 1.7
    },
    {
      "star": "TINORDI (S3)",
      "star_goals": 6.0,
      "star_assists": 4.0,
      "star_hits": 49.0,
      "season_number": 18,
      "points": 10.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 4.9
    },
    {
      "star": "TINORDI (S4)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 11.0,
      "season_number": 4,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 5.5
    },
    {
      "star": "TINORDI (S5)",
      "star_goals": 2.0,
      "star_assists": 2.0,
      "star_hits": 23.0,
      "season_number": 10,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 5.8
    },
    {
      "star": "TINORDI (S6)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 11.0,
      "season_number": 6,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 11.0
    },
    {
      "star": "TINORI (S3)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 11.0,
      "season_number": 3,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 11.0
    }
  ];