var coastersPlayers = [
    {
      "star": "ARCHIBALD",
      "star_goals": 14.0,
      "star_assists": 3.0,
      "star_hits": 18.0,
      "season_number": 43,
      "points": 17.0,
      "hat_trick": 1,
      "goals_in_game": 5.0,
      "assists_in_game": 1.0,
      "points_in_game": 5.0,
      "bruiser": 1.1
    },
    {
      "star": "BAILEY",
      "star_goals": 14.0,
      "star_assists": 7.0,
      "star_hits": 14.0,
      "season_number": 52,
      "points": 21.0,
      "hat_trick": 2,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.7
    },
    {
      "star": "BAPTISTE",
      "star_goals": 8.0,
      "star_assists": 6.0,
      "star_hits": 16.0,
      "season_number": 22,
      "points": 14.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 1.1
    },
    {
      "star": "BROWN",
      "star_goals": 24.0,
      "star_assists": 10.0,
      "star_hits": 40.0,
      "season_number": 63,
      "points": 34.0,
      "hat_trick": 2,
      "goals_in_game": 3.0,
      "assists_in_game": 4.0,
      "points_in_game": 6.0,
      "bruiser": 1.2
    },
    {
      "star": "BYFUGLIEN",
      "star_goals": 26.0,
      "star_assists": 30.0,
      "star_hits": 142.0,
      "season_number": 64,
      "points": 56.0,
      "hat_trick": 3,
      "goals_in_game": 4.0,
      "assists_in_game": 4.0,
      "points_in_game": 5.0,
      "bruiser": 2.5
    },

    {
      "star": "DUCLAIR",
      "star_goals": 43.0,
      "star_assists": 25.0,
      "star_hits": 90.0,
      "season_number": 138,
      "points": 68.0,
      "hat_trick": 5,
      "goals_in_game": 3.0,
      "assists_in_game": 3.0,
      "points_in_game": 5.0,
      "bruiser": 1.3
    },
    {
      "star": "EARL",
      "star_goals": 24.0,
      "star_assists": 18.0,
      "star_hits": 60.0,
      "season_number": 94,
      "points": 42.0,
      "hat_trick": 2,
      "goals_in_game": 4.0,
      "assists_in_game": 3.0,
      "points_in_game": 5.0,
      "bruiser": 1.4
    },
    {
      "star": "FORTUNUS",
      "star_goals": 4.0,
      "star_assists": 3.0,
      "star_hits": 3.0,
      "season_number": 10,
      "points": 7.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.4
    },
    {
      "star": "FRASER",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 1,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 0.0
    },
    {
      "star": "GEORGE",
      "star_goals": 6.0,
      "star_assists": 4.0,
      "star_hits": 3.0,
      "season_number": 29,
      "points": 10.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.3
    },


    {
      "star": "HO-SANG",
      "star_goals": 37.0,
      "star_assists": 20.0,
      "star_hits": 70.0,
      "season_number": 120,
      "points": 57.0,
      "hat_trick": 2,
      "goals_in_game": 3.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 1.2
    },

    {
      "star": "J. SUBBAN",
      "star_goals": 6.0,
      "star_assists": 4.0,
      "star_hits": 0.0,
      "season_number": 4,
      "points": 10.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.0
    },
    {
      "star": "JOSEPH",
      "star_goals": 35.0,
      "star_assists": 43.0,
      "star_hits": 92.0,
      "season_number": 86,
      "points": 78.0,
      "hat_trick": 3,
      "goals_in_game": 5.0,
      "assists_in_game": 5.0,
      "points_in_game": 6.0,
      "bruiser": 1.2
    },
    {
      "star": "KOLESAR",
      "star_goals": 3.0,
      "star_assists": 1.0,
      "star_hits": 3.0,
      "season_number": 14,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.8
    },
    {
      "star": "NURSE",
      "star_goals": 16.0,
      "star_assists": 21.0,
      "star_hits": 79.0,
      "season_number": 57,
      "points": 37.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 2.1
    },
    {
      "star": "SMITH",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 2.0,
      "season_number": 8,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.7
    },
    {
      "star": "SMITH-PELLY",
      "star_goals": 20.0,
      "star_assists": 11.0,
      "star_hits": 39.0,
      "season_number": 41,
      "points": 31.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 1.3
    },

    {
      "star": "SUESS",
      "star_goals": 3.0,
      "star_assists": 1.0,
      "star_hits": 6.0,
      "season_number": 12,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.5
    },
    {
      "star": "VAUGHAN",
      "star_goals": 3.0,
      "star_assists": 4.0,
      "star_hits": 14.0,
      "season_number": 18,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 2.0
    }
  ];

var coastersSeason = [
    {
      "star": "ARCHIBALD (S1)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 1,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "ARCHIBALD (S4)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 3.0,
      "season_number": 4,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.5
    },
    {
      "star": "ARCHIBALD (S5)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 2.0,
      "season_number": 5,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 1.0
    },
    {
      "star": "ARCHIBALD (S8)",
      "star_goals": 8.0,
      "star_assists": 0.0,
      "star_hits": 8.0,
      "season_number": 24,
      "points": 8.0,
      "hat_trick": 1,
      "goals_in_game": 5.0,
      "assists_in_game": 0.0,
      "points_in_game": 5.0,
      "bruiser": 1.0
    },
    {
      "star": "ARCHIBALD (S9)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 5.0,
      "season_number": 9,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 2.5
    },
    {
      "star": "BAILEY (S5)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 5,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "BAILEY (S6)",
      "star_goals": 4.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 12,
      "points": 5.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "BAILEY (S7)",
      "star_goals": 8.0,
      "star_assists": 5.0,
      "star_hits": 14.0,
      "season_number": 35,
      "points": 13.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 1.1
    },
    {
      "star": "BAPTISTE (S1)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 1,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 0.0
    },
    {
      "star": "BAPTISTE (S2)",
      "star_goals": 3.0,
      "star_assists": 3.0,
      "star_hits": 9.0,
      "season_number": 6,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 1.5
    },
    {
      "star": "BAPTISTE (S5)",
      "star_goals": 4.0,
      "star_assists": 3.0,
      "star_hits": 7.0,
      "season_number": 15,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 1.0
    },
    {
      "star": "BROWN (S1)",
      "star_goals": 3.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "BROWN (S2)",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 9.0,
      "season_number": 4,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 1.8
    },
    {
      "star": "BROWN (S4)",
      "star_goals": 6.0,
      "star_assists": 1.0,
      "star_hits": 11.0,
      "season_number": 20,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.6
    },
    {
      "star": "BROWN (S5)",
      "star_goals": 4.0,
      "star_assists": 1.0,
      "star_hits": 6.0,
      "season_number": 10,
      "points": 5.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 1.2
    },
    {
      "star": "BROWN (S6)",
      "star_goals": 3.0,
      "star_assists": 1.0,
      "star_hits": 5.0,
      "season_number": 12,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 1.2
    },
    {
      "star": "BROWN (S7)",
      "star_goals": 3.0,
      "star_assists": 0.0,
      "star_hits": 2.0,
      "season_number": 7,
      "points": 3.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 0.0,
      "points_in_game": 3.0,
      "bruiser": 0.7
    },
    {
      "star": "BROWN (S8)",
      "star_goals": 2.0,
      "star_assists": 4.0,
      "star_hits": 7.0,
      "season_number": 8,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 4.0,
      "points_in_game": 6.0,
      "bruiser": 1.2
    },
    {
      "star": "BYFUGLIEN (S1)",
      "star_goals": 6.0,
      "star_assists": 5.0,
      "star_hits": 0.0,
      "season_number": 5,
      "points": 11.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "BYFUGLIEN (S2)",
      "star_goals": 7.0,
      "star_assists": 10.0,
      "star_hits": 48.0,
      "season_number": 12,
      "points": 17.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 4.0,
      "points_in_game": 5.0,
      "bruiser": 2.8
    },
    {
      "star": "BYFUGLIEN (S3)",
      "star_goals": 3.0,
      "star_assists": 0.0,
      "star_hits": 5.0,
      "season_number": 3,
      "points": 3.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 0.0,
      "points_in_game": 3.0,
      "bruiser": 1.7
    },
    {
      "star": "BYFUGLIEN (S4)",
      "star_goals": 0.0,
      "star_assists": 1.0,
      "star_hits": 14.0,
      "season_number": 4,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 0.0,
      "assists_in_game": 1.0,
      "points_in_game": 1.0,
      "bruiser": 14.0
    },
    {
      "star": "BYFUGLIEN (S5)",
      "star_goals": 10.0,
      "star_assists": 14.0,
      "star_hits": 75.0,
      "season_number": 40,
      "points": 24.0,
      "hat_trick": 1,
      "goals_in_game": 4.0,
      "assists_in_game": 3.0,
      "points_in_game": 5.0,
      "bruiser": 3.1
    },
    {
      "star": "BYFULGIEN (S3)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 7.0,
      "season_number": 3,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 2.3
    },
    {
      "star": "DUCLAIR (S1)",
      "star_goals": 0.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 0.0,
      "hat_trick": 0,
      "goals_in_game": 0.0,
      "assists_in_game": 0.0,
      "points_in_game": 0.0,
      "bruiser": null
    },
    {
      "star": "DUCLAIR (S2)",
      "star_goals": 5.0,
      "star_assists": 4.0,
      "star_hits": 13.0,
      "season_number": 8,
      "points": 9.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 1.4
    },
    {
      "star": "DUCLAIR (S3)",
      "star_goals": 7.0,
      "star_assists": 5.0,
      "star_hits": 11.0,
      "season_number": 12,
      "points": 12.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.9
    },
    {
      "star": "DUCLAIR (S4)",
      "star_goals": 4.0,
      "star_assists": 3.0,
      "star_hits": 23.0,
      "season_number": 12,
      "points": 7.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 3.0,
      "points_in_game": 3.0,
      "bruiser": 3.3
    },
    {
      "star": "DUCLAIR (S5)",
      "star_goals": 5.0,
      "star_assists": 4.0,
      "star_hits": 9.0,
      "season_number": 15,
      "points": 9.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 5.0,
      "bruiser": 1.0
    },
    {
      "star": "DUCLAIR (S6)",
      "star_goals": 5.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 12,
      "points": 6.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "DUCLAIR (S7)",
      "star_goals": 8.0,
      "star_assists": 5.0,
      "star_hits": 20.0,
      "season_number": 35,
      "points": 13.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 1.5
    },
    {
      "star": "DUCLAIR (S8)",
      "star_goals": 7.0,
      "star_assists": 0.0,
      "star_hits": 10.0,
      "season_number": 24,
      "points": 7.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 0.0,
      "points_in_game": 3.0,
      "bruiser": 1.4
    },
    {
      "star": "DUCLAIR (S9)",
      "star_goals": 2.0,
      "star_assists": 3.0,
      "star_hits": 4.0,
      "season_number": 18,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.8
    },
    {
      "star": "EARL (S2)",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 5.0,
      "season_number": 4,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 1.0
    },
    {
      "star": "EARL (S3)",
      "star_goals": 3.0,
      "star_assists": 4.0,
      "star_hits": 8.0,
      "season_number": 6,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 5.0,
      "bruiser": 1.1
    },
    {
      "star": "EARL (S4)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 3.0,
      "season_number": 4,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.5
    },
    {
      "star": "EARL (S5)",
      "star_goals": 0.0,
      "star_assists": 3.0,
      "star_hits": 6.0,
      "season_number": 5,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 0.0,
      "assists_in_game": 3.0,
      "points_in_game": 3.0,
      "bruiser": 2.0
    },
    {
      "star": "EARL (S7)",
      "star_goals": 3.0,
      "star_assists": 1.0,
      "star_hits": 8.0,
      "season_number": 14,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 2.0
    },
    {
      "star": "EARL (S8)",
      "star_goals": 2.0,
      "star_assists": 3.0,
      "star_hits": 12.0,
      "season_number": 16,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 2.4
    },
    {
      "star": "EARL (S9)",
      "star_goals": 12.0,
      "star_assists": 4.0,
      "star_hits": 18.0,
      "season_number": 45,
      "points": 16.0,
      "hat_trick": 2,
      "goals_in_game": 4.0,
      "assists_in_game": 2.0,
      "points_in_game": 5.0,
      "bruiser": 1.1
    },
    {
      "star": "FORTUNUS (S1)",
      "star_goals": 0.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 1,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 0.0,
      "assists_in_game": 2.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "FORTUNUS (S2)",
      "star_goals": 3.0,
      "star_assists": 0.0,
      "star_hits": 3.0,
      "season_number": 2,
      "points": 3.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 0.0,
      "points_in_game": 3.0,
      "bruiser": 1.0
    },
    {
      "star": "FORTUNUS (S7)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 7,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "FRASER (S1)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 1,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 0.0
    },
    {
      "star": "GEORGE (S7)",
      "star_goals": 5.0,
      "star_assists": 2.0,
      "star_hits": 3.0,
      "season_number": 21,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.4
    },
    {
      "star": "GEORGE (S8)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 8,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "HI-SANG (S1)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 1,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 0.0
    },
    {
      "star": "HI-SANG (S4)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 6.0,
      "season_number": 4,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 3.0
    },
    {
      "star": "HO SANG (S3)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 5.0,
      "season_number": 3,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 2.5
    },
    {
      "star": "HO-SANG (S1)",
      "star_goals": 3.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "HO-SANG (S2)",
      "star_goals": 6.0,
      "star_assists": 7.0,
      "star_hits": 17.0,
      "season_number": 8,
      "points": 13.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 1.3
    },
    {
      "star": "HO-SANG (S3)",
      "star_goals": 5.0,
      "star_assists": 2.0,
      "star_hits": 2.0,
      "season_number": 9,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.3
    },
    {
      "star": "HO-SANG (S4)",
      "star_goals": 1.0,
      "star_assists": 3.0,
      "star_hits": 3.0,
      "season_number": 4,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.8
    },
    {
      "star": "HO-SANG (S5)",
      "star_goals": 12.0,
      "star_assists": 5.0,
      "star_hits": 19.0,
      "season_number": 35,
      "points": 17.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 1.1
    },
    {
      "star": "HO-SANG (S6)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 4.0,
      "season_number": 6,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 2.0
    },
    {
      "star": "HO-SANG (S7)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 8.0,
      "season_number": 14,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 2.7
    },
    {
      "star": "HO-SANG (S8)",
      "star_goals": 4.0,
      "star_assists": 0.0,
      "star_hits": 13.0,
      "season_number": 24,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 3.2
    },
    {
      "star": "HO-SANG (S9)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 4.0,
      "season_number": 18,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.3
    },
    {
      "star": "HOSANG (S10)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 5.0,
      "season_number": 10,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 1.7
    },
    {
      "star": "J. SUBBAN (S1)",
      "star_goals": 6.0,
      "star_assists": 4.0,
      "star_hits": 0.0,
      "season_number": 4,
      "points": 10.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.0
    },
    {
      "star": "JOSEPH (S1)",
      "star_goals": 5.0,
      "star_assists": 3.0,
      "star_hits": 0.0,
      "season_number": 3,
      "points": 8.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.0
    },
    {
      "star": "JOSEPH (S2)",
      "star_goals": 6.0,
      "star_assists": 9.0,
      "star_hits": 38.0,
      "season_number": 14,
      "points": 15.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 2.5
    },
    {
      "star": "JOSEPH (S3)",
      "star_goals": 9.0,
      "star_assists": 6.0,
      "star_hits": 3.0,
      "season_number": 9,
      "points": 15.0,
      "hat_trick": 2,
      "goals_in_game": 5.0,
      "assists_in_game": 3.0,
      "points_in_game": 6.0,
      "bruiser": 0.2
    },
    {
      "star": "JOSEPH (S4)",
      "star_goals": 5.0,
      "star_assists": 3.0,
      "star_hits": 8.0,
      "season_number": 8,
      "points": 8.0,
      "hat_trick": 1,
      "goals_in_game": 4.0,
      "assists_in_game": 2.0,
      "points_in_game": 5.0,
      "bruiser": 1.0
    },
    {
      "star": "JOSEPH (S5)",
      "star_goals": 5.0,
      "star_assists": 10.0,
      "star_hits": 14.0,
      "season_number": 20,
      "points": 15.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 5.0,
      "points_in_game": 6.0,
      "bruiser": 0.9
    },
    {
      "star": "JOSEPH (S6)",
      "star_goals": 2.0,
      "star_assists": 8.0,
      "star_hits": 16.0,
      "season_number": 18,
      "points": 10.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 4.0,
      "points_in_game": 4.0,
      "bruiser": 1.6
    },
    {
      "star": "JOSEPH (S7)",
      "star_goals": 3.0,
      "star_assists": 4.0,
      "star_hits": 13.0,
      "season_number": 14,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 1.9
    },
    {
      "star": "KOLESAR (S7)",
      "star_goals": 3.0,
      "star_assists": 1.0,
      "star_hits": 3.0,
      "season_number": 14,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.8
    },
    {
      "star": "NURSE (S1)",
      "star_goals": 1.0,
      "star_assists": 3.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "NURSE (S2)",
      "star_goals": 3.0,
      "star_assists": 3.0,
      "star_hits": 18.0,
      "season_number": 8,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 2.0,
      "bruiser": 3.0
    },
    {
      "star": "NURSE (S3)",
      "star_goals": 5.0,
      "star_assists": 5.0,
      "star_hits": 8.0,
      "season_number": 9,
      "points": 10.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.8
    },
    {
      "star": "NURSE (S5)",
      "star_goals": 3.0,
      "star_assists": 7.0,
      "star_hits": 33.0,
      "season_number": 20,
      "points": 10.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 3.0,
      "bruiser": 3.3
    },
    {
      "star": "NURSE (S6)",
      "star_goals": 4.0,
      "star_assists": 3.0,
      "star_hits": 20.0,
      "season_number": 18,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 2.9
    },
    {
      "star": "SMITH (S8)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 2.0,
      "season_number": 8,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.7
    },
    {
      "star": "SMITH-PELLY (S1)",
      "star_goals": 3.0,
      "star_assists": 4.0,
      "star_hits": 0.0,
      "season_number": 3,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "SMITH-PELLY (S2)",
      "star_goals": 7.0,
      "star_assists": 2.0,
      "star_hits": 17.0,
      "season_number": 8,
      "points": 9.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 1.9
    },
    {
      "star": "SMITH-PELLY (S3)",
      "star_goals": 2.0,
      "star_assists": 3.0,
      "star_hits": 4.0,
      "season_number": 6,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.8
    },
    {
      "star": "SMITH-PELLY (S4)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 4.0,
      "season_number": 8,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 2.0
    },
    {
      "star": "SMITH-PELLY (S5)",
      "star_goals": 4.0,
      "star_assists": 2.0,
      "star_hits": 8.0,
      "season_number": 10,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 1.3
    },
    {
      "star": "SMITH-PELLY (S6)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 6.0,
      "season_number": 6,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 3.0
    },
    {
      "star": "SUBBAN (S4)",
      "star_goals": 0.0,
      "star_assists": 12.0,
      "star_hits": 1000.0,
      "season_number": 4,
      "points": 12.0,
      "hat_trick": 0,
      "goals_in_game": 0.0,
      "assists_in_game": 12.0,
      "points_in_game": 12.0,
      "bruiser": 83.3
    },
    {
      "star": "SUBBAN (S6)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 6,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "SUBBAN (S9)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 3.0,
      "season_number": 9,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.5
    },
    {
      "star": "SUESS (S4)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 4,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "SUESS (S8)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 6.0,
      "season_number": 8,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 3.0
    },
    {
      "star": "VAUGHAN (S5)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 4.0,
      "season_number": 5,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 2.0
    },
    {
      "star": "VAUGHAN (S6)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 5.0,
      "season_number": 6,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 5.0
    },
    {
      "star": "VAUGHAN (S7)",
      "star_goals": 1.0,
      "star_assists": 3.0,
      "star_hits": 5.0,
      "season_number": 7,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 1.2
    }
  ];