var irelandPlayers = [
    {
      "star": "CHARMS",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 5.0,
      "season_number": 8,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 2.5
    },
    {
      "star": "FOGARTY",
      "star_goals": 14.0,
      "star_assists": 17.0,
      "star_hits": 63.0,
      "season_number": 76,
      "points": 31.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 5.0,
      "bruiser": 2.0
    },
    {
      "star": "MACEWEN",
      "star_goals": 7.0,
      "star_assists": 5.0,
      "star_hits": 22.0,
      "season_number": 36,
      "points": 12.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 1.8
    },

    {
      "star": "MCCARRON",
      "star_goals": 29.0,
      "star_assists": 17.0,
      "star_hits": 96.0,
      "season_number": 125,
      "points": 46.0,
      "hat_trick": 4,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 2.1
    },
    {
      "star": "MCCARTHY",
      "star_goals": 4.0,
      "star_assists": 6.0,
      "star_hits": 14.0,
      "season_number": 34,
      "points": 10.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 1.4
    },
    {
      "star": "MCCORMICK",
      "star_goals": 15.0,
      "star_assists": 14.0,
      "star_hits": 50.0,
      "season_number": 72,
      "points": 29.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 3.0,
      "points_in_game": 5.0,
      "bruiser": 1.7
    },
    {
      "star": "MCENENY",
      "star_goals": 9.0,
      "star_assists": 2.0,
      "star_hits": 53.0,
      "season_number": 33,
      "points": 11.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 4.8
    },
    {
      "star": "MURPHY",
      "star_goals": 11.0,
      "star_assists": 14.0,
      "star_hits": 65.0,
      "season_number": 65,
      "points": 25.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 2.6
    },
    {
      "star": "NEVILLE",
      "star_goals": 3.0,
      "star_assists": 5.0,
      "star_hits": 10.0,
      "season_number": 18,
      "points": 8.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 4.0,
      "points_in_game": 4.0,
      "bruiser": 1.2
    },

    {
      "star": "OBRIEN",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 7.0,
      "season_number": 17,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 1.4
    },
    {
      "star": "OCONNOR",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 7.0,
      "season_number": 14,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 1.4
    },
    {
      "star": "OREGAN",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 3.0,
      "season_number": 9,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.5
    },
    {
      "star": "OREILLY",
      "star_goals": 5.0,
      "star_assists": 3.0,
      "star_hits": 7.0,
      "season_number": 18,
      "points": 8.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.9
    },
    {
      "star": "OROURKE",
      "star_goals": 15.0,
      "star_assists": 6.0,
      "star_hits": 29.0,
      "season_number": 80,
      "points": 21.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 1.4
    },
    {
      "star": "OSEYLERY",
      "star_goals": 7.0,
      "star_assists": 6.0,
      "star_hits": 41.0,
      "season_number": 41,
      "points": 13.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 3.2
    },


    {
      "star": "SMALLENBERG",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 4.0,
      "season_number": 8,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 2.0
    }
  ];

var irelandSeason = [
    {
      "star": "CHARMS (S8)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 5.0,
      "season_number": 8,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 2.5
    },
    {
      "star": "FOGARTY (S4)",
      "star_goals": 2.0,
      "star_assists": 3.0,
      "star_hits": 9.0,
      "season_number": 8,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 1.8
    },
    {
      "star": "FOGARTY (S5)",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 12.0,
      "season_number": 10,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 2.4
    },
    {
      "star": "FOGARTY (S6)",
      "star_goals": 4.0,
      "star_assists": 4.0,
      "star_hits": 4.0,
      "season_number": 18,
      "points": 8.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.5
    },
    {
      "star": "FOGARTY (S7)",
      "star_goals": 2.0,
      "star_assists": 3.0,
      "star_hits": 6.0,
      "season_number": 7,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 5.0,
      "bruiser": 1.2
    },
    {
      "star": "FOGARTY (S8)",
      "star_goals": 2.0,
      "star_assists": 4.0,
      "star_hits": 22.0,
      "season_number": 24,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 2.0,
      "bruiser": 3.7
    },
    {
      "star": "FOGARTY (S9)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 10.0,
      "season_number": 9,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 5.0
    },
    {
      "star": "MACEWEN (S4)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 3.0,
      "season_number": 4,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 1.5
    },
    {
      "star": "MACEWEN (S5)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 1.0,
      "season_number": 5,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.5
    },
    {
      "star": "MACEWEN (S6)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 7.0,
      "season_number": 12,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 2.3
    },
    {
      "star": "MACEWEN (S7)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 9.0,
      "season_number": 7,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 3.0
    },
    {
      "star": "MACEWEN (S8)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 2.0,
      "season_number": 8,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.0
    },
    {
      "star": "MCCARON (S5)",
      "star_goals": 3.0,
      "star_assists": 0.0,
      "star_hits": 8.0,
      "season_number": 5,
      "points": 3.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 0.0,
      "points_in_game": 3.0,
      "bruiser": 2.7
    },
    {
      "star": "MCCARON (S8)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 7.0,
      "season_number": 8,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 3.5
    },
    {
      "star": "MCCARRON (S4)",
      "star_goals": 3.0,
      "star_assists": 0.0,
      "star_hits": 6.0,
      "season_number": 8,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 2.0
    },
    {
      "star": "MCCARRON (S5)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 10.0,
      "season_number": 10,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 3.3
    },
    {
      "star": "MCCARRON (S6)",
      "star_goals": 11.0,
      "star_assists": 3.0,
      "star_hits": 34.0,
      "season_number": 36,
      "points": 14.0,
      "hat_trick": 3,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 2.4
    },
    {
      "star": "MCCARRON (S7)",
      "star_goals": 6.0,
      "star_assists": 6.0,
      "star_hits": 17.0,
      "season_number": 28,
      "points": 12.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 1.4
    },
    {
      "star": "MCCARRON (S8)",
      "star_goals": 2.0,
      "star_assists": 4.0,
      "star_hits": 17.0,
      "season_number": 16,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 2.8
    },
    {
      "star": "MCCARRON (S9)",
      "star_goals": 6.0,
      "star_assists": 2.0,
      "star_hits": 12.0,
      "season_number": 27,
      "points": 8.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 1.0,
      "points_in_game": 4.0,
      "bruiser": 1.5
    },
    {
      "star": "MCCARTHY (S8)",
      "star_goals": 2.0,
      "star_assists": 2.0,
      "star_hits": 7.0,
      "season_number": 16,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.8
    },
    {
      "star": "MCCARTHY (S9)",
      "star_goals": 2.0,
      "star_assists": 4.0,
      "star_hits": 7.0,
      "season_number": 18,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 1.2
    },
    {
      "star": "MCCORMICK (S4)",
      "star_goals": 4.0,
      "star_assists": 5.0,
      "star_hits": 18.0,
      "season_number": 16,
      "points": 9.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 2.0
    },
    {
      "star": "MCCORMICK (S5)",
      "star_goals": 3.0,
      "star_assists": 3.0,
      "star_hits": 9.0,
      "season_number": 10,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 1.5
    },
    {
      "star": "MCCORMICK (S6)",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 12.0,
      "season_number": 12,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 2.4
    },
    {
      "star": "MCCORMICK (S7)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 2.0,
      "season_number": 7,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 2.0
    },
    {
      "star": "MCCORMICK (S9)",
      "star_goals": 4.0,
      "star_assists": 4.0,
      "star_hits": 9.0,
      "season_number": 27,
      "points": 8.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 5.0,
      "bruiser": 1.1
    },
    {
      "star": "MCENENY (S4)",
      "star_goals": 4.0,
      "star_assists": 1.0,
      "star_hits": 15.0,
      "season_number": 8,
      "points": 5.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 3.0
    },
    {
      "star": "MCENENY (S5)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 15.0,
      "season_number": 5,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 15.0
    },
    {
      "star": "MCENENY (S6)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 5.0,
      "season_number": 6,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 2.5
    },
    {
      "star": "MCENENY (S7)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 18.0,
      "season_number": 14,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 6.0
    },
    {
      "star": "MCINTYRE (S4)",
      "star_goals": 1.0,
      "star_assists": 28.0,
      "star_hits": 966.0,
      "season_number": 4,
      "points": 29.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 28.0,
      "points_in_game": 29.0,
      "bruiser": 33.3
    },
    {
      "star": "MCINTYRE (S6)",
      "star_goals": 2.0,
      "star_assists": 26.0,
      "star_hits": 0.929,
      "season_number": 6,
      "points": 28.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 26.0,
      "points_in_game": 28.0,
      "bruiser": 0.0
    },
    {
      "star": "MURPHY (S4)",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 9.0,
      "season_number": 8,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 1.8
    },
    {
      "star": "MURPHY (S5)",
      "star_goals": 3.0,
      "star_assists": 3.0,
      "star_hits": 9.0,
      "season_number": 10,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 1.5
    },
    {
      "star": "MURPHY (S7)",
      "star_goals": 3.0,
      "star_assists": 4.0,
      "star_hits": 24.0,
      "season_number": 21,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 3.4
    },
    {
      "star": "MURPHY (S8)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 10.0,
      "season_number": 8,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 5.0
    },
    {
      "star": "MURPHY (S9)",
      "star_goals": 1.0,
      "star_assists": 4.0,
      "star_hits": 13.0,
      "season_number": 18,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 2.6
    },
    {
      "star": "NEVILLE (S4)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 1.0,
      "season_number": 4,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 0.5
    },
    {
      "star": "NEVILLE (S7)",
      "star_goals": 1.0,
      "star_assists": 5.0,
      "star_hits": 9.0,
      "season_number": 14,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 4.0,
      "points_in_game": 4.0,
      "bruiser": 1.5
    },
    {
      "star": "O'REILLY (S6)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 5.0,
      "season_number": 6,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 2.5
    },
    {
      "star": "OBRIEN (S8)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 7.0,
      "season_number": 8,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 3.5
    },
    {
      "star": "OBRIEN (S9)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 9,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "OCONNOR (S7)",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 7.0,
      "season_number": 14,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 1.4
    },
    {
      "star": "OREGAN (S9)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 3.0,
      "season_number": 9,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.5
    },
    {
      "star": "OREILLY (S9)",
      "star_goals": 5.0,
      "star_assists": 3.0,
      "star_hits": 7.0,
      "season_number": 18,
      "points": 8.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.9
    },
    {
      "star": "OROURKE (S7)",
      "star_goals": 5.0,
      "star_assists": 4.0,
      "star_hits": 18.0,
      "season_number": 28,
      "points": 9.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 2.0
    },
    {
      "star": "OROURKE (S8)",
      "star_goals": 4.0,
      "star_assists": 1.0,
      "star_hits": 2.0,
      "season_number": 16,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.4
    },
    {
      "star": "OROURKE (S9)",
      "star_goals": 6.0,
      "star_assists": 1.0,
      "star_hits": 9.0,
      "season_number": 36,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.3
    },
    {
      "star": "OSEYLERY (S7)",
      "star_goals": 4.0,
      "star_assists": 1.0,
      "star_hits": 14.0,
      "season_number": 14,
      "points": 5.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 2.8
    },
    {
      "star": "OSEYLERY (S9)",
      "star_goals": 3.0,
      "star_assists": 5.0,
      "star_hits": 27.0,
      "season_number": 27,
      "points": 8.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 3.4
    },
    {
      "star": "O\u2019BRIEN (S5)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 1.0,
      "season_number": 5,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 0.5
    },
    {
      "star": "O\u2019BRIEN (S6)",
      "star_goals": 3.0,
      "star_assists": 1.0,
      "star_hits": 7.0,
      "season_number": 12,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.8
    },
    {
      "star": "O\u2019GARA (S6)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 14.0,
      "season_number": 12,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 4.7
    },
    {
      "star": "O\u2019REGAN (S4)",
      "star_goals": 0.0,
      "star_assists": 3.0,
      "star_hits": 2.0,
      "season_number": 4,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 0.0,
      "assists_in_game": 3.0,
      "points_in_game": 3.0,
      "bruiser": 0.7
    },
    {
      "star": "O\u2019REGAN (S5)",
      "star_goals": 0.0,
      "star_assists": 3.0,
      "star_hits": 2.0,
      "season_number": 5,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 0.0,
      "assists_in_game": 3.0,
      "points_in_game": 3.0,
      "bruiser": 0.7
    },
    {
      "star": "O\u2019REGAN (S6)",
      "star_goals": 3.0,
      "star_assists": 3.0,
      "star_hits": 3.0,
      "season_number": 12,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.5
    },
    {
      "star": "O\u2019REILLY (S4)",
      "star_goals": 6.0,
      "star_assists": 1.0,
      "star_hits": 12.0,
      "season_number": 12,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 1.7
    },
    {
      "star": "O\u2019REILLY (S5)",
      "star_goals": 4.0,
      "star_assists": 3.0,
      "star_hits": 7.0,
      "season_number": 10,
      "points": 7.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 1.0
    },
    {
      "star": "O\u2019REILLY (S6)",
      "star_goals": 7.0,
      "star_assists": 7.0,
      "star_hits": 24.0,
      "season_number": 36,
      "points": 14.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 1.7
    },
    {
      "star": "O\u2019REILLY (S7)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 4.0,
      "season_number": 7,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 2.0
    },
    {
      "star": "O\u2019REILLY (S8)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 5.0,
      "season_number": 8,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 2.5
    },
    {
      "star": "SMALLENBERG (S8)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 4.0,
      "season_number": 8,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 2.0
    }
  ];