var petesPlayers = [
    {
      "star": "ABBANDONATO",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 1.0,
      "season_number": 9,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.5
    },
    {
      "star": "CEHLARIK",
      "star_goals": 15.0,
      "star_assists": 6.0,
      "star_hits": 17.0,
      "season_number": 66,
      "points": 21.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 5.0,
      "bruiser": 0.8
    },
    {
      "star": "CERESNAK",
      "star_goals": 1.0,
      "star_assists": 3.0,
      "star_hits": 9.0,
      "season_number": 18,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 3.0,
      "bruiser": 2.2
    },
    {
      "star": "HOLIK",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 2.0,
      "season_number": 9,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 1.0
    },
    {
      "star": "HOLLAND",
      "star_goals": 14.0,
      "star_assists": 12.0,
      "star_hits": 24.0,
      "season_number": 84,
      "points": 26.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.9
    },
    {
      "star": "KOLOUCH",
      "star_goals": 2.0,
      "star_assists": 3.0,
      "star_hits": 2.0,
      "season_number": 16,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.4
    },
    {
      "star": "KUMSTAT",
      "star_goals": 4.0,
      "star_assists": 2.0,
      "star_hits": 3.0,
      "season_number": 17,
      "points": 6.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.5
    },
    {
      "star": "MACARTHUR",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 2.0,
      "season_number": 8,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.0
    },
    {
      "star": "MUELLER",
      "star_goals": 6.0,
      "star_assists": 12.0,
      "star_hits": 18.0,
      "season_number": 58,
      "points": 18.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 1.0
    },
    {
      "star": "PIETRANGELO",
      "star_goals": 3.0,
      "star_assists": 15.0,
      "star_hits": 30.0,
      "season_number": 48,
      "points": 18.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 1.7
    },
    {
      "star": "SIDLIK",
      "star_goals": 2.0,
      "star_assists": 7.0,
      "star_hits": 17.0,
      "season_number": 24,
      "points": 9.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 4.0,
      "points_in_game": 4.0,
      "bruiser": 1.9
    },
    {
      "star": "SIVAK",
      "star_goals": 3.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 16,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "STOYKEWYCH",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 6.0,
      "season_number": 8,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 6.0
    },
    {
      "star": "STRAPAC",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 8,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "TRSKA",
      "star_goals": 1.0,
      "star_assists": 4.0,
      "star_hits": 16.0,
      "season_number": 17,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 3.2
    },
    {
      "star": "VRANA",
      "star_goals": 9.0,
      "star_assists": 4.0,
      "star_hits": 13.0,
      "season_number": 43,
      "points": 13.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 1.0,
      "points_in_game": 4.0,
      "bruiser": 1.0
    },

    {
      "star": "KODAKPETE",
      "star_goals": 42.0,
      "star_assists": 23.0,
      "star_hits": 56.0,
      "season_number": 120,
      "points": 65.0,
      "hat_trick": 7,
      "goals_in_game": 7.0,
      "assists_in_game": 4.0,
      "points_in_game": 8.0,
      "bruiser": 0.9
    }
  ];

var petesSeason = [
    {
      "star": "ABBANDONATO (S9)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 1.0,
      "season_number": 9,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.5
    },
    {
      "star": "CEHLARIK (S8)",
      "star_goals": 12.0,
      "star_assists": 4.0,
      "star_hits": 10.0,
      "season_number": 48,
      "points": 16.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 5.0,
      "bruiser": 0.6
    },
    {
      "star": "CEHLARIK (S9)",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 7.0,
      "season_number": 18,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 1.4
    },
    {
      "star": "CERESNAK (S9)",
      "star_goals": 1.0,
      "star_assists": 3.0,
      "star_hits": 9.0,
      "season_number": 18,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 3.0,
      "bruiser": 2.2
    },
    {
      "star": "HOLIK (S9)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 2.0,
      "season_number": 9,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 1.0
    },
    {
      "star": "HOLLAND (S8)",
      "star_goals": 8.0,
      "star_assists": 7.0,
      "star_hits": 12.0,
      "season_number": 48,
      "points": 15.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.8
    },
    {
      "star": "HOLLAND (S9)",
      "star_goals": 6.0,
      "star_assists": 5.0,
      "star_hits": 12.0,
      "season_number": 36,
      "points": 11.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 1.1
    },
    {
      "star": "KOLOUCH (S8)",
      "star_goals": 2.0,
      "star_assists": 3.0,
      "star_hits": 2.0,
      "season_number": 16,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.4
    },
    {
      "star": "KUMSTAT (S8)",
      "star_goals": 3.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 8,
      "points": 3.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 0.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "KUMSTAT (S9)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 3.0,
      "season_number": 9,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 1.0
    },
    {
      "star": "MACARTHUR (S8)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 2.0,
      "season_number": 8,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.0
    },
    {
      "star": "MUELLER (S8)",
      "star_goals": 4.0,
      "star_assists": 9.0,
      "star_hits": 13.0,
      "season_number": 40,
      "points": 13.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 1.0
    },
    {
      "star": "MUELLER (S9)",
      "star_goals": 2.0,
      "star_assists": 3.0,
      "star_hits": 5.0,
      "season_number": 18,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 1.0
    },
    {
      "star": "PIETRANGELO (S8)",
      "star_goals": 3.0,
      "star_assists": 15.0,
      "star_hits": 30.0,
      "season_number": 48,
      "points": 18.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 1.7
    },
    {
      "star": "SIDLIK (S8)",
      "star_goals": 2.0,
      "star_assists": 7.0,
      "star_hits": 17.0,
      "season_number": 24,
      "points": 9.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 4.0,
      "points_in_game": 4.0,
      "bruiser": 1.9
    },
    {
      "star": "SIVAK (S8)",
      "star_goals": 3.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 16,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "STOYKEWYCH (S8)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 6.0,
      "season_number": 8,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 6.0
    },
    {
      "star": "STRAPAC (S8)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 8,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "TRSKA (S8)",
      "star_goals": 0.0,
      "star_assists": 1.0,
      "star_hits": 9.0,
      "season_number": 8,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 0.0,
      "assists_in_game": 1.0,
      "points_in_game": 1.0,
      "bruiser": 9.0
    },
    {
      "star": "TRSKA (S9)",
      "star_goals": 1.0,
      "star_assists": 3.0,
      "star_hits": 7.0,
      "season_number": 9,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 1.8
    },
    {
      "star": "VRANA (S8)",
      "star_goals": 4.0,
      "star_assists": 1.0,
      "star_hits": 2.0,
      "season_number": 16,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.4
    },
    {
      "star": "VRANA (S9)",
      "star_goals": 5.0,
      "star_assists": 3.0,
      "star_hits": 11.0,
      "season_number": 27,
      "points": 8.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 1.0,
      "points_in_game": 4.0,
      "bruiser": 1.4
    },

    {
      "star": "KODAKPETE (S8)",
      "star_goals": 42.0,
      "star_assists": 23.0,
      "star_hits": 56.0,
      "season_number": 120,
      "points": 65.0,
      "hat_trick": 7,
      "goals_in_game": 7.0,
      "assists_in_game": 4.0,
      "points_in_game": 8.0,
      "bruiser": 0.9
    }
  ];