var pinguinePlayers = [
    {
      "star": "BJUGSTAD",
      "star_goals": 3.0,
      "star_assists": 7.0,
      "star_hits": 0.0,
      "season_number": 5,
      "points": 10.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.0
    },
    {
      "star": "CROSBIE",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 1.0,
      "season_number": 5,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.3
    },
    {
      "star": "CROSBY",
      "star_goals": 14.0,
      "star_assists": 5.0,
      "star_hits": 0.0,
      "season_number": 5,
      "points": 19.0,
      "hat_trick": 2,
      "goals_in_game": 6.0,
      "assists_in_game": 2.0,
      "points_in_game": 7.0,
      "bruiser": 0.0
    },

    {
      "star": "CULLEN",
      "star_goals": 3.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 3,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "GUENTZEL",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 1,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "HORNQVIST",
      "star_goals": 5.0,
      "star_assists": 4.0,
      "star_hits": 0.0,
      "season_number": 6,
      "points": 9.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 4.0,
      "points_in_game": 4.0,
      "bruiser": 0.0
    },

    {
      "star": "JOHNSON",
      "star_goals": 4.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 6.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },

    {
      "star": "KESSEL",
      "star_goals": 3.0,
      "star_assists": 3.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.0
    },
    {
      "star": "LEMIEUETE",
      "star_goals": 16.0,
      "star_assists": 4.0,
      "star_hits": 11.0,
      "season_number": 12,
      "points": 20.0,
      "hat_trick": 3,
      "goals_in_game": 4.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.6
    },

    {
      "star": "LETANG",
      "star_goals": 0.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 0.0,
      "hat_trick": 0,
      "goals_in_game": 0.0,
      "assists_in_game": 0.0,
      "points_in_game": 0.0,
      "bruiser": null
    },
    {
      "star": "MAATA",
      "star_goals": 3.0,
      "star_assists": 4.0,
      "star_hits": 0.0,
      "season_number": 5,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "MALKIN",
      "star_goals": 2.0,
      "star_assists": 6.0,
      "star_hits": 0.0,
      "season_number": 3,
      "points": 8.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 5.0,
      "points_in_game": 5.0,
      "bruiser": 0.0
    },

    {
      "star": "RUST",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 1,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "SCHULTZ",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 1,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },

  ];

var pinguineSeason = [
    {
      "star": "BJUGSTAD (S1)",
      "star_goals": 3.0,
      "star_assists": 7.0,
      "star_hits": 0.0,
      "season_number": 5,
      "points": 10.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.0
    },
    {
      "star": "CROSBIE (S5)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 1.0,
      "season_number": 5,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.3
    },
    {
      "star": "CROSBY (S1)",
      "star_goals": 14.0,
      "star_assists": 5.0,
      "star_hits": 0.0,
      "season_number": 5,
      "points": 19.0,
      "hat_trick": 2,
      "goals_in_game": 6.0,
      "assists_in_game": 2.0,
      "points_in_game": 7.0,
      "bruiser": 0.0
    },

    {
      "star": "CULLEN (S1)",
      "star_goals": 3.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 3,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "GUENTZEL (S1)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 1,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "HORNQVIST (S1)",
      "star_goals": 5.0,
      "star_assists": 4.0,
      "star_hits": 0.0,
      "season_number": 6,
      "points": 9.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 4.0,
      "points_in_game": 4.0,
      "bruiser": 0.0
    },

    {
      "star": "JOHNSON (S1)",
      "star_goals": 4.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 6.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },

    {
      "star": "KESSEL (S1)",
      "star_goals": 3.0,
      "star_assists": 3.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.0
    },
    {
      "star": "LEMIEUETE (S1)",
      "star_goals": 5.0,
      "star_assists": 3.0,
      "star_hits": 0.0,
      "season_number": 4,
      "points": 8.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "LEMIEUETE (S2)",
      "star_goals": 11.0,
      "star_assists": 1.0,
      "star_hits": 11.0,
      "season_number": 8,
      "points": 12.0,
      "hat_trick": 2,
      "goals_in_game": 4.0,
      "assists_in_game": 1.0,
      "points_in_game": 4.0,
      "bruiser": 0.9
    },


    {
      "star": "LETANG (S1)",
      "star_goals": 0.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 0.0,
      "hat_trick": 0,
      "goals_in_game": 0.0,
      "assists_in_game": 0.0,
      "points_in_game": 0.0,
      "bruiser": null
    },
    {
      "star": "MAATA (S1)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 1,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "MAATA (S2)",
      "star_goals": 2.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 4,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "MALKIN (S1)",
      "star_goals": 2.0,
      "star_assists": 6.0,
      "star_hits": 0.0,
      "season_number": 3,
      "points": 8.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 5.0,
      "points_in_game": 5.0,
      "bruiser": 0.0
    },

    {
      "star": "RUST (S1)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 1,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "SCHULTZ (S1)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 1,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },

  ];