var r2lPlayers = [
    {
      "star": "AIOLI",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 3.0,
      "season_number": 6,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.0
    },
    {
      "star": "ASPLUND",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 4,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "BARKOV",
      "star_goals": 2.0,
      "star_assists": 7.0,
      "star_hits": 1.0,
      "season_number": 7,
      "points": 9.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 4.0,
      "points_in_game": 5.0,
      "bruiser": 0.1
    },
    {
      "star": "BLANDISI",
      "star_goals": 17.0,
      "star_assists": 7.0,
      "star_hits": 3.0,
      "season_number": 22,
      "points": 24.0,
      "hat_trick": 2,
      "goals_in_game": 6.0,
      "assists_in_game": 3.0,
      "points_in_game": 9.0,
      "bruiser": 0.1
    },
    {
      "star": "CAMISKEY",
      "star_goals": 1.0,
      "star_assists": 4.0,
      "star_hits": 8.0,
      "season_number": 8,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 1.6
    },
    {
      "star": "DI GIUSEPPE",
      "star_goals": 2.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 4,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "ERIKKSON EK",
      "star_goals": 9.0,
      "star_assists": 3.0,
      "star_hits": 3.0,
      "season_number": 10,
      "points": 12.0,
      "hat_trick": 2,
      "goals_in_game": 4.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.2
    },

    {
      "star": "FAKSA",
      "star_goals": 16.0,
      "star_assists": 13.0,
      "star_hits": 19.0,
      "season_number": 35,
      "points": 29.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 3.0,
      "points_in_game": 5.0,
      "bruiser": 0.7
    },
    {
      "star": "FRK",
      "star_goals": 11.0,
      "star_assists": 16.0,
      "star_hits": 9.0,
      "season_number": 36,
      "points": 27.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 4.0,
      "points_in_game": 5.0,
      "bruiser": 0.3
    },
    {
      "star": "GEORGE",
      "star_goals": 2.0,
      "star_assists": 3.0,
      "star_hits": 4.0,
      "season_number": 4,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.8
    },
    {
      "star": "HARDEN",
      "star_goals": 19.0,
      "star_assists": 17.0,
      "star_hits": 24.0,
      "season_number": 31,
      "points": 36.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.7
    },
    {
      "star": "HICKEY",
      "star_goals": 2.0,
      "star_assists": 4.0,
      "star_hits": 9.0,
      "season_number": 8,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 1.5
    },
    {
      "star": "HULAK",
      "star_goals": 5.0,
      "star_assists": 1.0,
      "star_hits": 3.0,
      "season_number": 9,
      "points": 6.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 1.0,
      "points_in_game": 4.0,
      "bruiser": 0.5
    },
    {
      "star": "LYUBUSHKIN",
      "star_goals": 4.0,
      "star_assists": 11.0,
      "star_hits": 14.0,
      "season_number": 20,
      "points": 15.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 5.0,
      "points_in_game": 5.0,
      "bruiser": 0.9
    },
    {
      "star": "MARSHALL",
      "star_goals": 12.0,
      "star_assists": 2.0,
      "star_hits": 6.0,
      "season_number": 12,
      "points": 14.0,
      "hat_trick": 1,
      "goals_in_game": 4.0,
      "assists_in_game": 1.0,
      "points_in_game": 5.0,
      "bruiser": 0.4
    },
    {
      "star": "MESSI",
      "star_goals": 9.0,
      "star_assists": 5.0,
      "star_hits": 6.0,
      "season_number": 10,
      "points": 14.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.4
    },
    {
      "star": "NUTIVAARA",
      "star_goals": 3.0,
      "star_assists": 4.0,
      "star_hits": 4.0,
      "season_number": 5,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.6
    },
    {
      "star": "PIETRANGELO",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 4.0,
      "season_number": 4,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 2.0
    },
    {
      "star": "POBLETE",
      "star_goals": 48.0,
      "star_assists": 24.0,
      "star_hits": 42.0,
      "season_number": 50,
      "points": 72.0,
      "hat_trick": 6,
      "goals_in_game": 4.0,
      "assists_in_game": 3.0,
      "points_in_game": 5.0,
      "bruiser": 0.6
    },
    {
      "star": "SGARBOSSA",
      "star_goals": 9.0,
      "star_assists": 7.0,
      "star_hits": 7.0,
      "season_number": 19,
      "points": 16.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.4
    },
    {
      "star": "TOLVANEN",
      "star_goals": 25.0,
      "star_assists": 29.0,
      "star_hits": 10.0,
      "season_number": 44,
      "points": 54.0,
      "hat_trick": 2,
      "goals_in_game": 3.0,
      "assists_in_game": 4.0,
      "points_in_game": 4.0,
      "bruiser": 0.2
    },
    {
      "star": "TYNAN",
      "star_goals": 10.0,
      "star_assists": 4.0,
      "star_hits": 3.0,
      "season_number": 9,
      "points": 14.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.2
    },
    {
      "star": "VESALAINEN",
      "star_goals": 7.0,
      "star_assists": 2.0,
      "star_hits": 4.0,
      "season_number": 14,
      "points": 9.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.4
    },
    {
      "star": "WIDEMAN",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 3.0,
      "season_number": 2,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 1.5
    },
    {
      "star": "WOTHERSPOON",
      "star_goals": 5.0,
      "star_assists": 7.0,
      "star_hits": 13.0,
      "season_number": 17,
      "points": 12.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 1.1
    }
  ];

var r2lSeason = [
    {
      "star": "AIOLI (S2)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 3.0,
      "season_number": 2,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 3.0
    },
    {
      "star": "AIOLI (S4)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 4,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "ASPLUND (S4)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 4,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "BARKOV (S1)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 3,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "BARKOV (S2)",
      "star_goals": 1.0,
      "star_assists": 6.0,
      "star_hits": 1.0,
      "season_number": 4,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 4.0,
      "points_in_game": 5.0,
      "bruiser": 0.1
    },
    {
      "star": "BLANDISI (S3)",
      "star_goals": 9.0,
      "star_assists": 6.0,
      "star_hits": 3.0,
      "season_number": 9,
      "points": 15.0,
      "hat_trick": 1,
      "goals_in_game": 6.0,
      "assists_in_game": 3.0,
      "points_in_game": 9.0,
      "bruiser": 0.2
    },
    {
      "star": "BLANDISI (S4)",
      "star_goals": 4.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 8,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "BLANDISI (S5)",
      "star_goals": 4.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 5,
      "points": 4.0,
      "hat_trick": 1,
      "goals_in_game": 4.0,
      "assists_in_game": 0.0,
      "points_in_game": 4.0,
      "bruiser": 0.0
    },
    {
      "star": "CAMISKEY (S3)",
      "star_goals": 0.0,
      "star_assists": 1.0,
      "star_hits": 3.0,
      "season_number": 3,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 0.0,
      "assists_in_game": 1.0,
      "points_in_game": 1.0,
      "bruiser": 3.0
    },
    {
      "star": "CAMISKEY (S5)",
      "star_goals": 1.0,
      "star_assists": 3.0,
      "star_hits": 5.0,
      "season_number": 5,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 1.2
    },
    {
      "star": "DI GIUSEPPE (S1)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 1,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "DI GIUSEPPE (S3)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 3,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "ERIKKSON EK (S3)",
      "star_goals": 6.0,
      "star_assists": 2.0,
      "star_hits": 1.0,
      "season_number": 6,
      "points": 8.0,
      "hat_trick": 1,
      "goals_in_game": 4.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.1
    },
    {
      "star": "ERIKKSON EK (S4)",
      "star_goals": 3.0,
      "star_assists": 1.0,
      "star_hits": 2.0,
      "season_number": 4,
      "points": 4.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 1.0,
      "points_in_game": 4.0,
      "bruiser": 0.5
    },
    {
      "star": "ERIKSSON EK (S2)",
      "star_goals": 1.0,
      "star_assists": 21.0,
      "star_hits": 955.0,
      "season_number": 2,
      "points": 22.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 21.0,
      "points_in_game": 22.0,
      "bruiser": 43.4
    },
    {
      "star": "ERIKSSON EK (S5)",
      "star_goals": 6.0,
      "star_assists": 2.0,
      "star_hits": 2.0,
      "season_number": 10,
      "points": 8.0,
      "hat_trick": 1,
      "goals_in_game": 4.0,
      "assists_in_game": 1.0,
      "points_in_game": 5.0,
      "bruiser": 0.2
    },
    {
      "star": "ERIKSSON EK (S7)",
      "star_goals": 1020.0,
      "star_assists": 21.0,
      "star_hits": 9550.0,
      "season_number": 7,
      "points": 1041.0,
      "hat_trick": 1,
      "goals_in_game": 1020.0,
      "assists_in_game": 21.0,
      "points_in_game": 1041.0,
      "bruiser": 9.2
    },
    {
      "star": "FAKSA (S3)",
      "star_goals": 12.0,
      "star_assists": 12.0,
      "star_hits": 16.0,
      "season_number": 27,
      "points": 24.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 5.0,
      "bruiser": 0.7
    },
    {
      "star": "FAKSA (S4)",
      "star_goals": 4.0,
      "star_assists": 1.0,
      "star_hits": 3.0,
      "season_number": 8,
      "points": 5.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.6
    },
    {
      "star": "FRK (S4)",
      "star_goals": 8.0,
      "star_assists": 8.0,
      "star_hits": 2.0,
      "season_number": 16,
      "points": 16.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 4.0,
      "points_in_game": 5.0,
      "bruiser": 0.1
    },
    {
      "star": "FRK (S5)",
      "star_goals": 3.0,
      "star_assists": 8.0,
      "star_hits": 7.0,
      "season_number": 20,
      "points": 11.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.6
    },
    {
      "star": "GEORGE (S2)",
      "star_goals": 2.0,
      "star_assists": 3.0,
      "star_hits": 4.0,
      "season_number": 4,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.8
    },
    {
      "star": "HARDEN (S1)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 1,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 0.0
    },
    {
      "star": "HARDEN (S2)",
      "star_goals": 12.0,
      "star_assists": 14.0,
      "star_hits": 16.0,
      "season_number": 18,
      "points": 26.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.6
    },
    {
      "star": "HARDEN (S3)",
      "star_goals": 6.0,
      "star_assists": 3.0,
      "star_hits": 8.0,
      "season_number": 12,
      "points": 9.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.9
    },
    {
      "star": "HICKEY (S4)",
      "star_goals": 2.0,
      "star_assists": 4.0,
      "star_hits": 9.0,
      "season_number": 8,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 1.5
    },
    {
      "star": "HULAK (S4)",
      "star_goals": 3.0,
      "star_assists": 1.0,
      "star_hits": 1.0,
      "season_number": 4,
      "points": 4.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 1.0,
      "points_in_game": 4.0,
      "bruiser": 0.2
    },
    {
      "star": "HULAK (S5)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 2.0,
      "season_number": 5,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 1.0
    },
    {
      "star": "LYUBUSHKIN (S2)",
      "star_goals": 2.0,
      "star_assists": 3.0,
      "star_hits": 2.0,
      "season_number": 4,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 3.0,
      "bruiser": 0.4
    },
    {
      "star": "LYUBUSHKIN (S3)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 1.0,
      "season_number": 3,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.5
    },
    {
      "star": "LYUBUSHKIN (S4)",
      "star_goals": 1.0,
      "star_assists": 5.0,
      "star_hits": 5.0,
      "season_number": 8,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 5.0,
      "points_in_game": 5.0,
      "bruiser": 0.8
    },
    {
      "star": "LYUBUSHKIN (S5)",
      "star_goals": 0.0,
      "star_assists": 2.0,
      "star_hits": 6.0,
      "season_number": 5,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 0.0,
      "assists_in_game": 2.0,
      "points_in_game": 2.0,
      "bruiser": 3.0
    },
    {
      "star": "MARSHALL (S1)",
      "star_goals": 5.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 6.0,
      "hat_trick": 1,
      "goals_in_game": 4.0,
      "assists_in_game": 1.0,
      "points_in_game": 5.0,
      "bruiser": 0.0
    },
    {
      "star": "MARSHALL (S2)",
      "star_goals": 3.0,
      "star_assists": 0.0,
      "star_hits": 3.0,
      "season_number": 4,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 1.0
    },
    {
      "star": "MARSHALL (S3)",
      "star_goals": 4.0,
      "star_assists": 1.0,
      "star_hits": 3.0,
      "season_number": 6,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.6
    },
    {
      "star": "MESSI (S2)",
      "star_goals": 9.0,
      "star_assists": 5.0,
      "star_hits": 6.0,
      "season_number": 10,
      "points": 14.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.4
    },
    {
      "star": "NUTIVAARA (S1)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 1,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "NUTIVAARA (S2)",
      "star_goals": 2.0,
      "star_assists": 2.0,
      "star_hits": 4.0,
      "season_number": 4,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.0
    },
    {
      "star": "PIETRANGELO (S4)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 4.0,
      "season_number": 4,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 2.0
    },
    {
      "star": "POBLETE (S1)",
      "star_goals": 22.0,
      "star_assists": 8.0,
      "star_hits": 0.0,
      "season_number": 14,
      "points": 30.0,
      "hat_trick": 2,
      "goals_in_game": 4.0,
      "assists_in_game": 3.0,
      "points_in_game": 5.0,
      "bruiser": 0.0
    },
    {
      "star": "POBLETE (S2)",
      "star_goals": 17.0,
      "star_assists": 11.0,
      "star_hits": 25.0,
      "season_number": 18,
      "points": 28.0,
      "hat_trick": 3,
      "goals_in_game": 4.0,
      "assists_in_game": 3.0,
      "points_in_game": 5.0,
      "bruiser": 0.9
    },
    {
      "star": "POBLETE (S3)",
      "star_goals": 5.0,
      "star_assists": 2.0,
      "star_hits": 4.0,
      "season_number": 6,
      "points": 7.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 1.0,
      "points_in_game": 4.0,
      "bruiser": 0.6
    },
    {
      "star": "POBLETE (S4)",
      "star_goals": 4.0,
      "star_assists": 3.0,
      "star_hits": 13.0,
      "season_number": 12,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 1.9
    },
    {
      "star": "SGARBOSSA (S1)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 1,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "SGARBOSSA (S2)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 1.0,
      "season_number": 2,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.5
    },
    {
      "star": "SGARBOSSA (S3)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 2.0,
      "season_number": 3,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.0
    },
    {
      "star": "SGARBOSSA (S4)",
      "star_goals": 3.0,
      "star_assists": 4.0,
      "star_hits": 4.0,
      "season_number": 8,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.6
    },
    {
      "star": "SGARBOSSA (S5)",
      "star_goals": 3.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 5,
      "points": 3.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 0.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "TOLVANEN (S1)",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "TOLVANEN (S2)",
      "star_goals": 12.0,
      "star_assists": 15.0,
      "star_hits": 4.0,
      "season_number": 16,
      "points": 27.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 4.0,
      "points_in_game": 4.0,
      "bruiser": 0.1
    },
    {
      "star": "TOLVANEN (S3)",
      "star_goals": 5.0,
      "star_assists": 3.0,
      "star_hits": 3.0,
      "season_number": 9,
      "points": 8.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.4
    },
    {
      "star": "TOLVANEN (S4)",
      "star_goals": 3.0,
      "star_assists": 7.0,
      "star_hits": 1.0,
      "season_number": 12,
      "points": 10.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.1
    },
    {
      "star": "TOLVANEN (S5)",
      "star_goals": 2.0,
      "star_assists": 2.0,
      "star_hits": 2.0,
      "season_number": 5,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.5
    },
    {
      "star": "TYNAN (S1)",
      "star_goals": 4.0,
      "star_assists": 3.0,
      "star_hits": 0.0,
      "season_number": 3,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "TYNAN (S2)",
      "star_goals": 6.0,
      "star_assists": 1.0,
      "star_hits": 3.0,
      "season_number": 6,
      "points": 7.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.4
    },
    {
      "star": "VESALAINEN (S2)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "VESALAINEN (S3)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 3,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "VESALAINEN (S4)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 2.0,
      "season_number": 4,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 1.0
    },
    {
      "star": "VESALAINEN (S5)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 2.0,
      "season_number": 5,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 1.0
    },
    {
      "star": "WIDEMAN (S2)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 3.0,
      "season_number": 2,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 1.5
    },
    {
      "star": "WOTHERSPOON (S2)",
      "star_goals": 0.0,
      "star_assists": 2.0,
      "star_hits": 2.0,
      "season_number": 2,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 0.0,
      "assists_in_game": 2.0,
      "points_in_game": 2.0,
      "bruiser": 1.0
    },
    {
      "star": "WOTHERSPOON (S3)",
      "star_goals": 2.0,
      "star_assists": 3.0,
      "star_hits": 5.0,
      "season_number": 6,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 1.0
    },
    {
      "star": "WOTHERSPOON (S4)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 2.0,
      "season_number": 4,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.0
    },
    {
      "star": "WOTHERSPOON (S5)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 4.0,
      "season_number": 5,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 1.3
    }
  ];