var russiansPlayers = [
    {
      "star": "ANISIMOV",
      "star_goals": 28.0,
      "star_assists": 39.0,
      "star_hits": 25.0,
      "season_number": 73,
      "points": 67.0,
      "hat_trick": 3,
      "goals_in_game": 4.0,
      "assists_in_game": 4.0,
      "points_in_game": 7.0,
      "bruiser": 0.4
    },
    {
      "star": "ARTUSOV",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 4.0,
      "season_number": 14,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.8
    },
    {
      "star": "BARBASHEV",
      "star_goals": 17.0,
      "star_assists": 22.0,
      "star_hits": 8.0,
      "season_number": 52,
      "points": 39.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.2
    },
    {
      "star": "BILIK",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 4.0,
      "season_number": 7,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 1.3
    },
    {
      "star": "BUCHNEVICH",
      "star_goals": 16.0,
      "star_assists": 17.0,
      "star_hits": 12.0,
      "season_number": 51,
      "points": 33.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.4
    },

    {
      "star": "DADONOV",
      "star_goals": 23.0,
      "star_assists": 17.0,
      "star_hits": 17.0,
      "season_number": 76,
      "points": 40.0,
      "hat_trick": 1,
      "goals_in_game": 4.0,
      "assists_in_game": 4.0,
      "points_in_game": 5.0,
      "bruiser": 0.4
    },

    {
      "star": "EVANGETTHARE",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 3.0,
      "season_number": 18,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.6
    },

    {
      "star": "GABBARD",
      "star_goals": 3.0,
      "star_assists": 6.0,
      "star_hits": 38.0,
      "season_number": 40,
      "points": 9.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 4.0,
      "points_in_game": 4.0,
      "bruiser": 4.2
    },
    {
      "star": "GATTHESHOTOV",
      "star_goals": 7.0,
      "star_assists": 2.0,
      "star_hits": 8.0,
      "season_number": 33,
      "points": 9.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.9
    },
    {
      "star": "ISVERIHOTT",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 9,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "JACKANOV",
      "star_goals": 5.0,
      "star_assists": 19.0,
      "star_hits": 42.0,
      "season_number": 59,
      "points": 24.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 4.0,
      "points_in_game": 4.0,
      "bruiser": 1.8
    },
    {
      "star": "KAREERISOVA",
      "star_goals": 21.0,
      "star_assists": 21.0,
      "star_hits": 92.0,
      "season_number": 106,
      "points": 42.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 4.0,
      "points_in_game": 5.0,
      "bruiser": 2.2
    },

    {
      "star": "KOVALCHUK",
      "star_goals": 45.0,
      "star_assists": 43.0,
      "star_hits": 22.0,
      "season_number": 73,
      "points": 88.0,
      "hat_trick": 8,
      "goals_in_game": 4.0,
      "assists_in_game": 4.0,
      "points_in_game": 8.0,
      "bruiser": 0.2
    },
    {
      "star": "KUCHEROV",
      "star_goals": 68.0,
      "star_assists": 70.0,
      "star_hits": 72.0,
      "season_number": 144,
      "points": 138.0,
      "hat_trick": 5,
      "goals_in_game": 5.0,
      "assists_in_game": 4.0,
      "points_in_game": 9.0,
      "bruiser": 0.5
    },
    {
      "star": "LETUNOV",
      "star_goals": 5.0,
      "star_assists": 10.0,
      "star_hits": 13.0,
      "season_number": 40,
      "points": 15.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.9
    },

    {
      "star": "LYSZCZARCZYK",
      "star_goals": 3.0,
      "star_assists": 4.0,
      "star_hits": 4.0,
      "season_number": 23,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.6
    },
    {
      "star": "MALKIN",
      "star_goals": 18.0,
      "star_assists": 23.0,
      "star_hits": 28.0,
      "season_number": 74,
      "points": 41.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 5.0,
      "points_in_game": 6.0,
      "bruiser": 0.7
    },
    {
      "star": "NAMESTIKOV",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 1,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "NAMESTNIKOV",
      "star_goals": 5.0,
      "star_assists": 3.0,
      "star_hits": 1.0,
      "season_number": 16,
      "points": 8.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.1
    },
    {
      "star": "NICHUSHKIN",
      "star_goals": 9.0,
      "star_assists": 9.0,
      "star_hits": 0.0,
      "season_number": 24,
      "points": 18.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 4.0,
      "points_in_game": 4.0,
      "bruiser": 0.0
    },
    {
      "star": "ORLOV",
      "star_goals": 7.0,
      "star_assists": 10.0,
      "star_hits": 20.0,
      "season_number": 17,
      "points": 17.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 4.0,
      "points_in_game": 6.0,
      "bruiser": 1.2
    },
    {
      "star": "OSIPOV",
      "star_goals": 3.0,
      "star_assists": 5.0,
      "star_hits": 18.0,
      "season_number": 27,
      "points": 8.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 5.0,
      "bruiser": 2.2
    },
    {
      "star": "OVECHKIN",
      "star_goals": 16.0,
      "star_assists": 12.0,
      "star_hits": 25.0,
      "season_number": 54,
      "points": 28.0,
      "hat_trick": 2,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.9
    },
    {
      "star": "POBLETOV",
      "star_goals": 65.0,
      "star_assists": 41.0,
      "star_hits": 43.0,
      "season_number": 73,
      "points": 106.0,
      "hat_trick": 7,
      "goals_in_game": 7.0,
      "assists_in_game": 4.0,
      "points_in_game": 9.0,
      "bruiser": 0.4
    },
    {
      "star": "PUTIN",
      "star_goals": 10.0,
      "star_assists": 12.0,
      "star_hits": 16.0,
      "season_number": 38,
      "points": 22.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 4.0,
      "points_in_game": 5.0,
      "bruiser": 0.7
    },
    {
      "star": "SVECHNIKOV",
      "star_goals": 16.0,
      "star_assists": 9.0,
      "star_hits": 31.0,
      "season_number": 74,
      "points": 25.0,
      "hat_trick": 2,
      "goals_in_game": 4.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 1.2
    },

    {
      "star": "THENETOV",
      "star_goals": 4.0,
      "star_assists": 3.0,
      "star_hits": 3.0,
      "season_number": 9,
      "points": 7.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.4
    },

    {
      "star": "WHATTAMIRAKOLTU",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 2.0,
      "season_number": 9,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.0
    },

    {
      "star": "ZADOROV",
      "star_goals": 16.0,
      "star_assists": 22.0,
      "star_hits": 38.0,
      "season_number": 65,
      "points": 38.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 3.0,
      "points_in_game": 5.0,
      "bruiser": 1.0
    },
    {
      "star": "ZHIDKIKH",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 7,
      "points": 5.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 5.0,
      "bruiser": 0.0
    }
  ];

var russiansSeason = [
    {
      "star": "ANISIMOV (S4)",
      "star_goals": 12.0,
      "star_assists": 20.0,
      "star_hits": 6.0,
      "season_number": 28,
      "points": 32.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 4.0,
      "points_in_game": 7.0,
      "bruiser": 0.2
    },
    {
      "star": "ANISIMOV (S5)",
      "star_goals": 16.0,
      "star_assists": 19.0,
      "star_hits": 19.0,
      "season_number": 45,
      "points": 35.0,
      "hat_trick": 2,
      "goals_in_game": 4.0,
      "assists_in_game": 4.0,
      "points_in_game": 6.0,
      "bruiser": 0.5
    },
    {
      "star": "ARTUSOV (S7)",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 4.0,
      "season_number": 14,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.8
    },
    {
      "star": "BARBASHEV (S1)",
      "star_goals": 5.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 6.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "BARBASHEV (S2)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "BARBASHEV (S4)",
      "star_goals": 3.0,
      "star_assists": 11.0,
      "star_hits": 3.0,
      "season_number": 16,
      "points": 14.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.2
    },
    {
      "star": "BARBASHEV (S5)",
      "star_goals": 7.0,
      "star_assists": 4.0,
      "star_hits": 4.0,
      "season_number": 20,
      "points": 11.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.4
    },
    {
      "star": "BARBASHEV (S6)",
      "star_goals": 1.0,
      "star_assists": 4.0,
      "star_hits": 1.0,
      "season_number": 12,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 3.0,
      "bruiser": 0.2
    },
    {
      "star": "BILIK (S7)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 4.0,
      "season_number": 7,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 1.3
    },
    {
      "star": "BUCHNEVICH (S1)",
      "star_goals": 1.0,
      "star_assists": 3.0,
      "star_hits": 0.0,
      "season_number": 1,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.0
    },
    {
      "star": "BUCHNEVICH (S2)",
      "star_goals": 2.0,
      "star_assists": 2.0,
      "star_hits": 2.0,
      "season_number": 6,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.5
    },
    {
      "star": "BUCHNEVICH (S3)",
      "star_goals": 4.0,
      "star_assists": 5.0,
      "star_hits": 3.0,
      "season_number": 12,
      "points": 9.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.3
    },
    {
      "star": "BUCHNEVICH (S4)",
      "star_goals": 5.0,
      "star_assists": 4.0,
      "star_hits": 3.0,
      "season_number": 16,
      "points": 9.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.3
    },
    {
      "star": "BUCHNEVICH (S5)",
      "star_goals": 2.0,
      "star_assists": 2.0,
      "star_hits": 3.0,
      "season_number": 10,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 2.0,
      "bruiser": 0.8
    },
    {
      "star": "BUCHNEVICH (S6)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 1.0,
      "season_number": 6,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.3
    },
    {
      "star": "DADANOV (S4)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 3.0,
      "season_number": 4,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 3.0
    },
    {
      "star": "DADONOV (S2)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "DADONOV (S3)",
      "star_goals": 1.0,
      "star_assists": 5.0,
      "star_hits": 1.0,
      "season_number": 6,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 4.0,
      "points_in_game": 4.0,
      "bruiser": 0.2
    },
    {
      "star": "DADONOV (S4)",
      "star_goals": 5.0,
      "star_assists": 6.0,
      "star_hits": 2.0,
      "season_number": 16,
      "points": 11.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.2
    },
    {
      "star": "DADONOV (S5)",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 2.0,
      "season_number": 10,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.4
    },
    {
      "star": "DADONOV (S6)",
      "star_goals": 12.0,
      "star_assists": 4.0,
      "star_hits": 12.0,
      "season_number": 42,
      "points": 16.0,
      "hat_trick": 1,
      "goals_in_game": 4.0,
      "assists_in_game": 1.0,
      "points_in_game": 5.0,
      "bruiser": 0.8
    },
    {
      "star": "DADOROV (S2)",
      "star_goals": 0.0,
      "star_assists": 3.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 0.0,
      "assists_in_game": 3.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "EVANGETTHARE (S9)",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 3.0,
      "season_number": 18,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.6
    },
    {
      "star": "EVENGETTHARE (S7)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 2.0,
      "season_number": 7,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 2.0
    },
    {
      "star": "GABBARD (S10)",
      "star_goals": 0.0,
      "star_assists": 2.0,
      "star_hits": 10.0,
      "season_number": 10,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 0.0,
      "assists_in_game": 2.0,
      "points_in_game": 2.0,
      "bruiser": 5.0
    },
    {
      "star": "GABBARD (S6)",
      "star_goals": 1.0,
      "star_assists": 4.0,
      "star_hits": 17.0,
      "season_number": 12,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 4.0,
      "points_in_game": 4.0,
      "bruiser": 3.4
    },
    {
      "star": "GABBARD (S9)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 11.0,
      "season_number": 18,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 5.5
    },
    {
      "star": "GATTHESHOTOV (S8)",
      "star_goals": 6.0,
      "star_assists": 2.0,
      "star_hits": 6.0,
      "season_number": 24,
      "points": 8.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.8
    },
    {
      "star": "GATTHESHOTOV (S9)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 2.0,
      "season_number": 9,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 2.0
    },
    {
      "star": "ISVERIHOTT (S9)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 9,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "JACKANOV (S1)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 3,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "JACKANOV (S5)",
      "star_goals": 0.0,
      "star_assists": 8.0,
      "star_hits": 8.0,
      "season_number": 10,
      "points": 8.0,
      "hat_trick": 0,
      "goals_in_game": 0.0,
      "assists_in_game": 4.0,
      "points_in_game": 4.0,
      "bruiser": 1.0
    },
    {
      "star": "JACKANOV (S6)",
      "star_goals": 0.0,
      "star_assists": 2.0,
      "star_hits": 8.0,
      "season_number": 6,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 0.0,
      "assists_in_game": 2.0,
      "points_in_game": 2.0,
      "bruiser": 4.0
    },
    {
      "star": "JACKANOV (S7)",
      "star_goals": 2.0,
      "star_assists": 5.0,
      "star_hits": 10.0,
      "season_number": 14,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 4.0,
      "points_in_game": 4.0,
      "bruiser": 1.4
    },
    {
      "star": "JACKANOV (S8)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 4.0,
      "season_number": 8,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 4.0
    },
    {
      "star": "JACKANOV (S9)",
      "star_goals": 0.0,
      "star_assists": 3.0,
      "star_hits": 12.0,
      "season_number": 18,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 0.0,
      "assists_in_game": 2.0,
      "points_in_game": 2.0,
      "bruiser": 4.0
    },
    {
      "star": "KAREERISOVA (S1)",
      "star_goals": 5.0,
      "star_assists": 3.0,
      "star_hits": 0.0,
      "season_number": 3,
      "points": 8.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.0
    },
    {
      "star": "KAREERISOVA (S2)",
      "star_goals": 3.0,
      "star_assists": 0.0,
      "star_hits": 15.0,
      "season_number": 4,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 5.0
    },
    {
      "star": "KAREERISOVA (S5)",
      "star_goals": 4.0,
      "star_assists": 1.0,
      "star_hits": 21.0,
      "season_number": 15,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 4.2
    },
    {
      "star": "KAREERISOVA (S6)",
      "star_goals": 4.0,
      "star_assists": 8.0,
      "star_hits": 21.0,
      "season_number": 36,
      "points": 12.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 1.8
    },
    {
      "star": "KAREERISOVA (S7)",
      "star_goals": 2.0,
      "star_assists": 5.0,
      "star_hits": 14.0,
      "season_number": 14,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 4.0,
      "points_in_game": 5.0,
      "bruiser": 2.0
    },
    {
      "star": "KAREERISOVA (S8)",
      "star_goals": 2.0,
      "star_assists": 2.0,
      "star_hits": 9.0,
      "season_number": 16,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 2.0,
      "bruiser": 2.2
    },
    {
      "star": "KAREERISOVA (S9)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 12.0,
      "season_number": 18,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 2.0,
      "bruiser": 4.0
    },
    {
      "star": "KOVALCHUCK (S2)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 1.0,
      "season_number": 2,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 0.5
    },
    {
      "star": "KOVALCHUK (S2)",
      "star_goals": 9.0,
      "star_assists": 11.0,
      "star_hits": 3.0,
      "season_number": 10,
      "points": 20.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 4.0,
      "points_in_game": 7.0,
      "bruiser": 0.1
    },
    {
      "star": "KOVALCHUK (S3)",
      "star_goals": 14.0,
      "star_assists": 16.0,
      "star_hits": 11.0,
      "season_number": 27,
      "points": 30.0,
      "hat_trick": 2,
      "goals_in_game": 3.0,
      "assists_in_game": 4.0,
      "points_in_game": 5.0,
      "bruiser": 0.4
    },
    {
      "star": "KOVALCHUK (S4)",
      "star_goals": 22.0,
      "star_assists": 16.0,
      "star_hits": 8.0,
      "season_number": 36,
      "points": 38.0,
      "hat_trick": 5,
      "goals_in_game": 4.0,
      "assists_in_game": 4.0,
      "points_in_game": 8.0,
      "bruiser": 0.2
    },
    {
      "star": "KUCHEROV (S1)",
      "star_goals": 9.0,
      "star_assists": 6.0,
      "star_hits": 0.0,
      "season_number": 6,
      "points": 15.0,
      "hat_trick": 1,
      "goals_in_game": 4.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.0
    },
    {
      "star": "KUCHEROV (S2)",
      "star_goals": 7.0,
      "star_assists": 19.0,
      "star_hits": 27.0,
      "season_number": 18,
      "points": 26.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 4.0,
      "points_in_game": 5.0,
      "bruiser": 1.0
    },
    {
      "star": "KUCHEROV (S3)",
      "star_goals": 10.0,
      "star_assists": 7.0,
      "star_hits": 15.0,
      "season_number": 18,
      "points": 17.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.9
    },
    {
      "star": "KUCHEROV (S4)",
      "star_goals": 30.0,
      "star_assists": 25.0,
      "star_hits": 16.0,
      "season_number": 52,
      "points": 55.0,
      "hat_trick": 3,
      "goals_in_game": 5.0,
      "assists_in_game": 4.0,
      "points_in_game": 9.0,
      "bruiser": 0.3
    },
    {
      "star": "KUCHEROV (S5)",
      "star_goals": 6.0,
      "star_assists": 6.0,
      "star_hits": 8.0,
      "season_number": 20,
      "points": 12.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.7
    },
    {
      "star": "KUCHEROV (S6)",
      "star_goals": 6.0,
      "star_assists": 7.0,
      "star_hits": 6.0,
      "season_number": 30,
      "points": 13.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.5
    },
    {
      "star": "LETUNOV (S7)",
      "star_goals": 1.0,
      "star_assists": 6.0,
      "star_hits": 8.0,
      "season_number": 14,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 1.1
    },
    {
      "star": "LETUNOV (S8)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 1.0,
      "season_number": 8,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 0.5
    },
    {
      "star": "LETUNOV (S9)",
      "star_goals": 2.0,
      "star_assists": 4.0,
      "star_hits": 4.0,
      "season_number": 18,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.7
    },
    {
      "star": "LYSZCZARCYK (S7)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 3.0,
      "season_number": 7,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 3.0
    },
    {
      "star": "LYSZCZARCZYK (S7)",
      "star_goals": 2.0,
      "star_assists": 3.0,
      "star_hits": 2.0,
      "season_number": 14,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.4
    },
    {
      "star": "LYSZCZARCZYK (S9)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 2.0,
      "season_number": 9,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.0
    },
    {
      "star": "MALKIN (S1)",
      "star_goals": 3.0,
      "star_assists": 4.0,
      "star_hits": 0.0,
      "season_number": 5,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "MALKIN (S7)",
      "star_goals": 6.0,
      "star_assists": 4.0,
      "star_hits": 13.0,
      "season_number": 21,
      "points": 10.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 1.3
    },
    {
      "star": "MALKIN (S8)",
      "star_goals": 9.0,
      "star_assists": 15.0,
      "star_hits": 15.0,
      "season_number": 48,
      "points": 24.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 5.0,
      "points_in_game": 6.0,
      "bruiser": 0.6
    },
    {
      "star": "NAMESTIKOV (S1)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 1,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "NAMESTNIKOV (S4)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 4,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "NAMESTNIKOV (S6)",
      "star_goals": 4.0,
      "star_assists": 2.0,
      "star_hits": 1.0,
      "season_number": 12,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.2
    },
    {
      "star": "NICHUSHKIN (S1)",
      "star_goals": 4.0,
      "star_assists": 6.0,
      "star_hits": 0.0,
      "season_number": 5,
      "points": 10.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 4.0,
      "points_in_game": 4.0,
      "bruiser": 0.0
    },
    {
      "star": "NICHUSHKIN (S3)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 3,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 0.0
    },
    {
      "star": "NICHUSHKIN (S4)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 4,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "NICHUSHKIN (S6)",
      "star_goals": 2.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 12,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "ORLOV (S3)",
      "star_goals": 5.0,
      "star_assists": 3.0,
      "star_hits": 17.0,
      "season_number": 9,
      "points": 8.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 2.1
    },
    {
      "star": "ORLOV (S4)",
      "star_goals": 2.0,
      "star_assists": 7.0,
      "star_hits": 3.0,
      "season_number": 8,
      "points": 9.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 4.0,
      "points_in_game": 6.0,
      "bruiser": 0.3
    },
    {
      "star": "OSIPOV (S10)",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 3.0,
      "season_number": 10,
      "points": 5.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 5.0,
      "bruiser": 0.6
    },
    {
      "star": "OSIPOV (S8)",
      "star_goals": 0.0,
      "star_assists": 2.0,
      "star_hits": 6.0,
      "season_number": 8,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 0.0,
      "assists_in_game": 2.0,
      "points_in_game": 2.0,
      "bruiser": 3.0
    },
    {
      "star": "OSIPOV (S9)",
      "star_goals": 0.0,
      "star_assists": 1.0,
      "star_hits": 9.0,
      "season_number": 9,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 0.0,
      "assists_in_game": 1.0,
      "points_in_game": 1.0,
      "bruiser": 9.0
    },
    {
      "star": "OVECHKIN (S5)",
      "star_goals": 12.0,
      "star_assists": 8.0,
      "star_hits": 21.0,
      "season_number": 30,
      "points": 20.0,
      "hat_trick": 2,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 1.1
    },
    {
      "star": "OVECHKIN (S6)",
      "star_goals": 4.0,
      "star_assists": 4.0,
      "star_hits": 4.0,
      "season_number": 24,
      "points": 8.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.5
    },
    {
      "star": "POBLETOV (S1)",
      "star_goals": 6.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 4,
      "points": 8.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "POBLETOV (S2)",
      "star_goals": 29.0,
      "star_assists": 15.0,
      "star_hits": 17.0,
      "season_number": 18,
      "points": 44.0,
      "hat_trick": 4,
      "goals_in_game": 7.0,
      "assists_in_game": 4.0,
      "points_in_game": 9.0,
      "bruiser": 0.4
    },
    {
      "star": "POBLETOV (S3)",
      "star_goals": 24.0,
      "star_assists": 17.0,
      "star_hits": 23.0,
      "season_number": 39,
      "points": 41.0,
      "hat_trick": 3,
      "goals_in_game": 4.0,
      "assists_in_game": 3.0,
      "points_in_game": 6.0,
      "bruiser": 0.6
    },
    {
      "star": "POBLETOV (S4)",
      "star_goals": 6.0,
      "star_assists": 7.0,
      "star_hits": 3.0,
      "season_number": 12,
      "points": 13.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 5.0,
      "bruiser": 0.2
    },
    {
      "star": "PUTIN (S2)",
      "star_goals": 3.0,
      "star_assists": 4.0,
      "star_hits": 1.0,
      "season_number": 4,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 4.0,
      "points_in_game": 5.0,
      "bruiser": 0.1
    },
    {
      "star": "PUTIN (S4)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 1.0,
      "season_number": 4,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 0.5
    },
    {
      "star": "PUTIN (S7)",
      "star_goals": 2.0,
      "star_assists": 4.0,
      "star_hits": 6.0,
      "season_number": 14,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 1.0
    },
    {
      "star": "PUTIN (S8)",
      "star_goals": 3.0,
      "star_assists": 4.0,
      "star_hits": 8.0,
      "season_number": 16,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 1.1
    },
    {
      "star": "SVECHNIKOV (S7)",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 3.0,
      "season_number": 14,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.6
    },
    {
      "star": "SVECHNIKOV (S8)",
      "star_goals": 6.0,
      "star_assists": 4.0,
      "star_hits": 10.0,
      "season_number": 24,
      "points": 10.0,
      "hat_trick": 1,
      "goals_in_game": 4.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 1.0
    },
    {
      "star": "SVECHNIKOV (S9)",
      "star_goals": 7.0,
      "star_assists": 3.0,
      "star_hits": 18.0,
      "season_number": 36,
      "points": 10.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 1.8
    },

    {
      "star": "THENETOV (S1)",
      "star_goals": 3.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 1,
      "points": 3.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 0.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "THENETOV (S8)",
      "star_goals": 1.0,
      "star_assists": 3.0,
      "star_hits": 3.0,
      "season_number": 8,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.8
    },

    {
      "star": "WHATTAMIRAKOLTU (S9)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 2.0,
      "season_number": 9,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.0
    },
    {
      "star": "ZADAROV (S3)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 7.0,
      "season_number": 3,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 3.5
    },
    {
      "star": "ZADOROV (S1)",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "ZADOROV (S2)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "ZADOROV (S4)",
      "star_goals": 4.0,
      "star_assists": 3.0,
      "star_hits": 7.0,
      "season_number": 8,
      "points": 7.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 5.0,
      "bruiser": 1.0
    },
    {
      "star": "ZADOROV (S5)",
      "star_goals": 1.0,
      "star_assists": 7.0,
      "star_hits": 14.0,
      "season_number": 15,
      "points": 8.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 3.0,
      "bruiser": 1.8
    },
    {
      "star": "ZADOROV (S6)",
      "star_goals": 4.0,
      "star_assists": 9.0,
      "star_hits": 6.0,
      "season_number": 24,
      "points": 13.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.5
    },
    {
      "star": "ZADOROV (S7)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 11.0,
      "season_number": 14,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 5.5
    },
    {
      "star": "ZHIDKIKH (S7)",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 7,
      "points": 5.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 5.0,
      "bruiser": 0.0
    }
  ];