var scoutPlayers = [

    {
      "star": "AUBE-KUBEL",
      "star_goals": 5.0,
      "star_assists": 3.0,
      "star_hits": 9.0,
      "season_number": 34,
      "points": 8.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 1.1
    },
    {
      "star": "BOUCHER",
      "star_goals": 11.0,
      "star_assists": 4.0,
      "star_hits": 13.0,
      "season_number": 17,
      "points": 15.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.9
    },
    {
      "star": "CARR",
      "star_goals": 3.0,
      "star_assists": 13.0,
      "star_hits": 9.0,
      "season_number": 11,
      "points": 16.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 5.0,
      "points_in_game": 5.0,
      "bruiser": 0.6
    },
    {
      "star": "DAL COLLE",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 3.0,
      "season_number": 8,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 1.0
    },
    {
      "star": "DOTY",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 9,
      "points": 5.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 5.0,
      "bruiser": 0.0
    },
    {
      "star": "FRK",
      "star_goals": 30.0,
      "star_assists": 26.0,
      "star_hits": 82.0,
      "season_number": 93,
      "points": 56.0,
      "hat_trick": 3,
      "goals_in_game": 3.0,
      "assists_in_game": 4.0,
      "points_in_game": 5.0,
      "bruiser": 1.5
    },

    {
      "star": "GARDINER",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 3,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },

    {
      "star": "GERBE",
      "star_goals": 1.0,
      "star_assists": 3.0,
      "star_hits": 5.0,
      "season_number": 9,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 1.2
    },
    {
      "star": "GOALETE",
      "star_goals": 27.0,
      "star_assists": 20.0,
      "star_hits": 40.0,
      "season_number": 39,
      "points": 47.0,
      "hat_trick": 4,
      "goals_in_game": 4.0,
      "assists_in_game": 5.0,
      "points_in_game": 7.0,
      "bruiser": 0.9
    },
    {
      "star": "GRIFFITH",
      "star_goals": 3.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 3,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
  
    {
      "star": "HALBGEWACHS",
      "star_goals": 6.0,
      "star_assists": 0.0,
      "star_hits": 5.0,
      "season_number": 7,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 0.8
    },
    {
      "star": "JOLY",
      "star_goals": 2.0,
      "star_assists": 4.0,
      "star_hits": 0.0,
      "season_number": 9,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 4.0,
      "points_in_game": 6.0,
      "bruiser": 0.0
    },
    {
      "star": "JURCO",
      "star_goals": 8.0,
      "star_assists": 6.0,
      "star_hits": 20.0,
      "season_number": 15,
      "points": 14.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 1.4
    },

    {
      "star": "KOSTIN",
      "star_goals": 21.0,
      "star_assists": 14.0,
      "star_hits": 63.0,
      "season_number": 103,
      "points": 35.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 1.8
    },

    {
      "star": "KUBICA",
      "star_goals": 3.0,
      "star_assists": 1.0,
      "star_hits": 3.0,
      "season_number": 17,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.8
    },
    {
      "star": "KULDA",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 4,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },

    {
      "star": "LAFFERTY",
      "star_goals": 2.0,
      "star_assists": 2.0,
      "star_hits": 6.0,
      "season_number": 6,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 1.5
    },

    {
      "star": "LETTIERI",
      "star_goals": 7.0,
      "star_assists": 5.0,
      "star_hits": 12.0,
      "season_number": 10,
      "points": 12.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 5.0,
      "bruiser": 1.0
    },

    {
      "star": "MCILRAITH",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 0.0
    },

    {
      "star": "MOULSON",
      "star_goals": 2.0,
      "star_assists": 2.0,
      "star_hits": 2.0,
      "season_number": 5,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.5
    },
    {
      "star": "PALAT",
      "star_goals": 26.0,
      "star_assists": 30.0,
      "star_hits": 74.0,
      "season_number": 50,
      "points": 56.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 5.0,
      "points_in_game": 5.0,
      "bruiser": 1.3
    },
    {
      "star": "PU",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 6.0,
      "season_number": 9,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 3.0
    },
    {
      "star": "PUEMPEL",
      "star_goals": 6.0,
      "star_assists": 6.0,
      "star_hits": 34.0,
      "season_number": 41,
      "points": 12.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 2.8
    },


    {
      "star": "REDDEKOPP",
      "star_goals": 3.0,
      "star_assists": 7.0,
      "star_hits": 26.0,
      "season_number": 33,
      "points": 10.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 3.0,
      "bruiser": 2.6
    },
    {
      "star": "REDLICH",
      "star_goals": 2.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 9,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.0
    },


    {
      "star": "SIELOFF",
      "star_goals": 5.0,
      "star_assists": 4.0,
      "star_hits": 38.0,
      "season_number": 35,
      "points": 9.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 4.2
    },
    {
      "star": "TERRY",
      "star_goals": 8.0,
      "star_assists": 9.0,
      "star_hits": 42.0,
      "season_number": 18,
      "points": 17.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 4.0,
      "points_in_game": 4.0,
      "bruiser": 2.5
    }
  ]
  
  let scoutSeason = [
    {
      "star": "AUBE-KUBEL (S8)",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 12.0,
      "season_number": 24,
      "points": 5.0,
      "hat_trick": 0,
      "star_points": 5.0,
      "bruiser": 9.0,
      "hat_tricks": 0,
      "goals_in_game": 1.0,
      "points_in_game": 2.0
    },
    {
      "star": "AUBE-KUBEL (S9)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 1.0,
      "season_number": 9,
      "points": 3.0,
      "hat_trick": 0,
      "star_points": 3.0,
      "bruiser": 0.3,
      "hat_tricks": 0,
      "goals_in_game": 1.0,
      "points_in_game": 3.0
    },
    {
      "star": "BOUCHER (S1)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 3.0,
      "hat_trick": 0,
      "star_points": 3.0,
      "bruiser": 0.0,
      "hat_tricks": 0,
      "goals_in_game": 1.0,
      "points_in_game": 2.0
    },
    {
      "star": "BOUCHER (S2)",
      "star_goals": 5.0,
      "star_assists": 0.0,
      "star_hits": 9.0,
      "season_number": 6,
      "points": 5.0,
      "hat_trick": 0,
      "star_points": 5.0,
      "bruiser": 6.0,
      "hat_tricks": 0,
      "goals_in_game": 2.0,
      "points_in_game": 2.0
    },
    {
      "star": "BOUCHER (S3)",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 3.0,
      "season_number": 6,
      "points": 5.0,
      "hat_trick": 0,
      "star_points": 5.0,
      "bruiser": 1.5,
      "hat_tricks": 0,
      "goals_in_game": 2.0,
      "points_in_game": 3.0
    },
    {
      "star": "CARR (S3)",
      "star_goals": 0.0,
      "star_assists": 5.0,
      "star_hits": 0.0,
      "season_number": 3,
      "points": 5.0,
      "hat_trick": 0,
      "star_points": 5.0,
      "bruiser": 0.0,
      "hat_tricks": 0,
      "goals_in_game": 0.0,
      "points_in_game": 5.0
    },
    {
      "star": "DAL COLLE (S8)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 3.0,
      "season_number": 8,
      "points": 3.0,
      "hat_trick": 0,
      "star_points": 3.0,
      "bruiser": 1.0,
      "hat_tricks": 0,
      "goals_in_game": 2.0,
      "points_in_game": 3.0
    },
    {
      "star": "DOTY (S9)",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 9,
      "points": 5.0,
      "hat_trick": 1,
      "star_points": 5.0,
      "bruiser": 0.0,
      "hat_tricks": 1,
      "goals_in_game": 3.0,
      "points_in_game": 5.0
    },
    {
      "star": "FRK (S1)",
      "star_goals": 5.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 6.0,
      "hat_trick": 1,
      "star_points": 6.0,
      "bruiser": 0.0,
      "hat_tricks": 1,
      "goals_in_game": 4.0,
      "points_in_game": 5.0
    },
    {
      "star": "FRK (S2)",
      "star_goals": 6.0,
      "star_assists": 1.0,
      "star_hits": 6.0,
      "season_number": 6,
      "points": 7.0,
      "hat_trick": 1,
      "star_points": 7.0,
      "bruiser": 2.0,
      "hat_tricks": 1,
      "goals_in_game": 3.0,
      "points_in_game": 3.0
    },
    {
      "star": "FRK (S3)",
      "star_goals": 6.0,
      "star_assists": 6.0,
      "star_hits": 5.0,
      "season_number": 9,
      "points": 12.0,
      "hat_trick": 1,
      "star_points": 12.0,
      "bruiser": 1.1,
      "hat_tricks": 1,
      "goals_in_game": 3.0,
      "points_in_game": 5.0
    },
    {
      "star": "FRK (S7)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 13.0,
      "season_number": 7,
      "points": 3.0,
      "hat_trick": 0,
      "star_points": 3.0,
      "bruiser": 4.3,
      "hat_tricks": 0,
      "goals_in_game": 2.0,
      "points_in_game": 3.0
    },
    {
      "star": "FRK (S8)",
      "star_goals": 4.0,
      "star_assists": 4.0,
      "star_hits": 16.0,
      "season_number": 24,
      "points": 8.0,
      "hat_trick": 0,
      "star_points": 8.0,
      "bruiser": 7.0,
      "hat_tricks": 0,
      "goals_in_game": 2.0,
      "points_in_game": 4.0
    },
    {
      "star": "FRK (S9)",
      "star_goals": 5.0,
      "star_assists": 2.0,
      "star_hits": 19.0,
      "season_number": 27,
      "points": 7.0,
      "hat_trick": 0,
      "star_points": 7.0,
      "bruiser": 8.5,
      "hat_tricks": 0,
      "goals_in_game": 2.0,
      "points_in_game": 3.0
    },
    {
      "star": "GOALETE (S3)",
      "star_goals": 14.0,
      "star_assists": 11.0,
      "star_hits": 29.0,
      "season_number": 24,
      "points": 25.0,
      "hat_trick": 1,
      "star_points": 25.0,
      "bruiser": 13.2,
      "hat_tricks": 1,
      "goals_in_game": 4.0,
      "points_in_game": 7.0
    },
    {
      "star": "GRIFFITH (S1)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 3.0,
      "hat_trick": 0,
      "star_points": 3.0,
      "bruiser": 0.0,
      "hat_tricks": 0,
      "goals_in_game": 1.0,
      "points_in_game": 2.0
    },
  
    {
      "star": "JOLY (S9)",
      "star_goals": 2.0,
      "star_assists": 4.0,
      "star_hits": 0.0,
      "season_number": 9,
      "points": 6.0,
      "hat_trick": 0,
      "star_points": 6.0,
      "bruiser": 0.0,
      "hat_tricks": 0,
      "goals_in_game": 2.0,
      "points_in_game": 6.0
    },
    {
      "star": "JURCO (S3)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 1.0,
      "season_number": 3,
      "points": 3.0,
      "hat_trick": 0,
      "star_points": 3.0,
      "bruiser": 0.3,
      "hat_tricks": 0,
      "goals_in_game": 2.0,
      "points_in_game": 3.0
    },
    {
      "star": "KOSTIN (S5)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 10.0,
      "season_number": 5,
      "points": 2.0,
      "hat_trick": 0,
      "star_points": 2.0,
      "bruiser": 5.0,
      "hat_tricks": 0,
      "goals_in_game": 1.0,
      "points_in_game": 2.0
    },
    {
      "star": "KOSTIN (S7)",
      "star_goals": 5.0,
      "star_assists": 4.0,
      "star_hits": 24.0,
      "season_number": 28,
      "points": 9.0,
      "hat_trick": 0,
      "star_points": 9.0,
      "bruiser": 17.7,
      "hat_tricks": 0,
      "goals_in_game": 2.0,
      "points_in_game": 4.0
    },
    {
      "star": "KOSTIN (S8)",
      "star_goals": 6.0,
      "star_assists": 6.0,
      "star_hits": 20.0,
      "season_number": 32,
      "points": 12.0,
      "hat_trick": 0,
      "star_points": 12.0,
      "bruiser": 7.6,
      "hat_tricks": 0,
      "goals_in_game": 2.0,
      "points_in_game": 4.0
    },
    {
      "star": "KOSTIN (S9)",
      "star_goals": 5.0,
      "star_assists": 0.0,
      "star_hits": 7.0,
      "season_number": 18,
      "points": 5.0,
      "hat_trick": 1,
      "star_points": 5.0,
      "bruiser": 2.5,
      "hat_tricks": 1,
      "goals_in_game": 3.0,
      "points_in_game": 3.0
    },
    {
      "star": "KUBICA (S8)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 2.0,
      "season_number": 8,
      "points": 2.0,
      "hat_trick": 0,
      "star_points": 2.0,
      "bruiser": 1.0,
      "hat_tricks": 0,
      "goals_in_game": 1.0,
      "points_in_game": 2.0
    },
    {
      "star": "KULDA (S3)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 3,
      "points": 3.0,
      "hat_trick": 0,
      "star_points": 3.0,
      "bruiser": 0.0,
      "hat_tricks": 0,
      "goals_in_game": 1.0,
      "points_in_game": 3.0
    },
    {
      "star": "LAFFERTY (S3)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 3.0,
      "season_number": 3,
      "points": 3.0,
      "hat_trick": 0,
      "star_points": 3.0,
      "bruiser": 1.0,
      "hat_tricks": 0,
      "goals_in_game": 1.0,
      "points_in_game": 3.0
    },
    {
      "star": "MCILRAITH (S2)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 1.0,
      "hat_trick": 0,
      "star_points": 1.0,
      "bruiser": 0.0,
      "hat_tricks": 0,
      "goals_in_game": 1.0,
      "points_in_game": 1.0
    },
    {
      "star": "MOULSON (S3)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 2.0,
      "season_number": 3,
      "points": 1.0,
      "hat_trick": 0,
      "star_points": 1.0,
      "bruiser": 2.0,
      "hat_tricks": 0,
      "goals_in_game": 1.0,
      "points_in_game": 1.0
    },
    {
      "star": "PALAT (S2)",
      "star_goals": 5.0,
      "star_assists": 5.0,
      "star_hits": 22.0,
      "season_number": 8,
      "points": 10.0,
      "hat_trick": 0,
      "star_points": 10.0,
      "bruiser": 14.4,
      "hat_tricks": 0,
      "goals_in_game": 2.0,
      "points_in_game": 5.0
    },
    {
      "star": "PALAT (S3)",
      "star_goals": 7.0,
      "star_assists": 10.0,
      "star_hits": 9.0,
      "season_number": 18,
      "points": 17.0,
      "hat_trick": 0,
      "star_points": 17.0,
      "bruiser": 3.3,
      "hat_tricks": 0,
      "goals_in_game": 2.0,
      "points_in_game": 4.0
    },
    {
      "star": "PU (S9)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 6.0,
      "season_number": 9,
      "points": 2.0,
      "hat_trick": 0,
      "star_points": 2.0,
      "bruiser": 3.0,
      "hat_tricks": 0,
      "goals_in_game": 2.0,
      "points_in_game": 2.0
    },
    {
      "star": "PUEMPEL (S8)",
      "star_goals": 2.0,
      "star_assists": 4.0,
      "star_hits": 5.0,
      "season_number": 16,
      "points": 6.0,
      "hat_trick": 0,
      "star_points": 6.0,
      "bruiser": 2.0,
      "hat_tricks": 0,
      "goals_in_game": 1.0,
      "points_in_game": 4.0
    },
    {
      "star": "REDDEKOPP (S8)",
      "star_goals": 1.0,
      "star_assists": 4.0,
      "star_hits": 12.0,
      "season_number": 16,
      "points": 5.0,
      "hat_trick": 0,
      "star_points": 5.0,
      "bruiser": 4.8,
      "hat_tricks": 0,
      "goals_in_game": 1.0,
      "points_in_game": 3.0
    },
    {
      "star": "REDDEKOPP (S9)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 6.0,
      "season_number": 9,
      "points": 2.0,
      "hat_trick": 0,
      "star_points": 2.0,
      "bruiser": 3.0,
      "hat_tricks": 0,
      "goals_in_game": 2.0,
      "points_in_game": 2.0
    },
    {
      "star": "REDLICH (S9)",
      "star_goals": 2.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 9,
      "points": 4.0,
      "hat_trick": 0,
      "star_points": 4.0,
      "bruiser": 0.0,
      "hat_tricks": 0,
      "goals_in_game": 2.0,
      "points_in_game": 4.0
    },

    {
      "star": "SIELOFF (S6)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 10.0,
      "season_number": 6,
      "points": 3.0,
      "hat_trick": 0,
      "star_points": 3.0,
      "bruiser": 3.3,
      "hat_tricks": 0,
      "goals_in_game": 1.0,
      "points_in_game": 3.0
    },
    {
      "star": "SIELOFF (S7)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 9.0,
      "season_number": 7,
      "points": 1.0,
      "hat_trick": 0,
      "star_points": 1.0,
      "bruiser": 9.0,
      "hat_tricks": 0,
      "goals_in_game": 1.0,
      "points_in_game": 1.0
    },
    {
      "star": "SIELOFF (S8)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 7.0,
      "season_number": 8,
      "points": 1.0,
      "hat_trick": 0,
      "star_points": 1.0,
      "bruiser": 7.0,
      "hat_tricks": 0,
      "goals_in_game": 1.0,
      "points_in_game": 1.0
    },
    {
      "star": "TERRY (S2)",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 16.0,
      "season_number": 6,
      "points": 5.0,
      "hat_trick": 0,
      "star_points": 5.0,
      "bruiser": 12.0,
      "hat_tricks": 0,
      "goals_in_game": 2.0,
      "points_in_game": 2.0
    },
    {
      "star": "TERRY (S3)",
      "star_goals": 0.0,
      "star_assists": 4.0,
      "star_hits": 0.0,
      "season_number": 3,
      "points": 4.0,
      "hat_trick": 0,
      "star_points": 4.0,
      "bruiser": 0.0,
      "hat_tricks": 0,
      "goals_in_game": 0.0,
      "points_in_game": 4.0
    }
  ]
  