var spappersPlayers = [

    {
      "star": "ALZNER",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 2.0,
      "season_number": 2,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.7
    },
    {
      "star": "ANDALE",
      "star_goals": 4.0,
      "star_assists": 2.0,
      "star_hits": 3.0,
      "season_number": 11,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.5
    },
    {
      "star": "APPLETON",
      "star_goals": 3.0,
      "star_assists": 1.0,
      "star_hits": 5.0,
      "season_number": 18,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.2
    },
    {
      "star": "BAILEY",
      "star_goals": 8.0,
      "star_assists": 7.0,
      "star_hits": 33.0,
      "season_number": 16,
      "points": 15.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 2.2
    },

    {
      "star": "CORPTON SCANDLE",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 8,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 0.0
    },
    {
      "star": "ECKER",
      "star_goals": 20.0,
      "star_assists": 10.0,
      "star_hits": 25.0,
      "season_number": 66,
      "points": 30.0,
      "hat_trick": 3,
      "goals_in_game": 4.0,
      "assists_in_game": 3.0,
      "points_in_game": 7.0,
      "bruiser": 0.8
    },
    {
      "star": "ENGLUND",
      "star_goals": 2.0,
      "star_assists": 3.0,
      "star_hits": 2.0,
      "season_number": 12,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 2.0,
      "bruiser": 0.4
    },
    {
      "star": "FUCHS",
      "star_goals": 5.0,
      "star_assists": 4.0,
      "star_hits": 1.0,
      "season_number": 15,
      "points": 9.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.1
    },
    {
      "star": "HABERSTICH",
      "star_goals": 5.0,
      "star_assists": 8.0,
      "star_hits": 3.0,
      "season_number": 17,
      "points": 13.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 3.0,
      "bruiser": 0.2
    },
    {
      "star": "HABERSTITCH",
      "star_goals": 3.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 4,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "HIRANO",
      "star_goals": 6.0,
      "star_assists": 3.0,
      "star_hits": 4.0,
      "season_number": 21,
      "points": 9.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.4
    },
    {
      "star": "JEROFEJEVS",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 2.0,
      "season_number": 4,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.7
    },
    {
      "star": "JEVPALOVS",
      "star_goals": 4.0,
      "star_assists": 3.0,
      "star_hits": 3.0,
      "season_number": 26,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.4
    },
    {
      "star": "KATO",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 1.0,
      "season_number": 3,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.3
    },
    {
      "star": "KOBAYASHI",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 2.0,
      "season_number": 9,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.7
    },
    {
      "star": "NAURIS ZUSEVICS",
      "star_goals": 4.0,
      "star_assists": 4.0,
      "star_hits": 3.0,
      "season_number": 12,
      "points": 8.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.4
    },
    {
      "star": "OUELLET",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 2.0,
      "season_number": 7,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.4
    },
    {
      "star": "OULLET",
      "star_goals": 0.0,
      "star_assists": 3.0,
      "star_hits": 0.0,
      "season_number": 1,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 0.0,
      "assists_in_game": 3.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "SIEGENTHALER",
      "star_goals": 4.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 4.0,
      "hat_trick": 1,
      "goals_in_game": 4.0,
      "assists_in_game": 0.0,
      "points_in_game": 4.0,
      "bruiser": 0.0
    },
    {
      "star": "SUGIHARA",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 1.0,
      "season_number": 4,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.2
    },
    {
      "star": "TAMARA",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 1,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "TANAKA",
      "star_goals": 3.0,
      "star_assists": 0.0,
      "star_hits": 3.0,
      "season_number": 4,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 1.0
    },
    {
      "star": "TOJI",
      "star_goals": 32.0,
      "star_assists": 35.0,
      "star_hits": 32.0,
      "season_number": 45,
      "points": 67.0,
      "hat_trick": 3,
      "goals_in_game": 3.0,
      "assists_in_game": 4.0,
      "points_in_game": 5.0,
      "bruiser": 0.5
    },
    {
      "star": "WAKABAYASHI",
      "star_goals": 4.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 18,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },

    {
      "star": "YANDLE",
      "star_goals": 10.0,
      "star_assists": 11.0,
      "star_hits": 4.0,
      "season_number": 42,
      "points": 21.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.2
    },
    {
      "star": "YOSHIDA",
      "star_goals": 5.0,
      "star_assists": 3.0,
      "star_hits": 4.0,
      "season_number": 19,
      "points": 8.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.5
    }
  ];

var spappersSeason = [
    {
      "star": "ALLEN-GOALIE (S2)",
      "star_goals": 0.0,
      "star_assists": 0.0,
      "star_hits": 1.0,
      "season_number": 2,
      "points": 0.0,
      "hat_trick": 0,
      "goals_in_game": 0.0,
      "assists_in_game": 0.0,
      "points_in_game": 0.0,
      "bruiser": null
    },
    {
      "star": "ALZNER (S2)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 2.0,
      "season_number": 2,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.7
    },
    {
      "star": "ANDALE (S5)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 3.0,
      "season_number": 5,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 1.0
    },
    {
      "star": "ANDALE (S6)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 6,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "APPLETON (S10)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 3.0,
      "season_number": 10,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.5
    },
    {
      "star": "APPLETON (S8)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 2.0,
      "season_number": 8,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 1.0
    },
    {
      "star": "BAILEY (S2)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 31.0,
      "season_number": 4,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 10.3
    },
    {
      "star": "BAILEY (S3)",
      "star_goals": 6.0,
      "star_assists": 6.0,
      "star_hits": 2.0,
      "season_number": 12,
      "points": 12.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.2
    },
    
    {
      "star": "CORPTON SCANDLE (S8)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 8,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 0.0
    },
    {
      "star": "ECKER (S6)",
      "star_goals": 6.0,
      "star_assists": 3.0,
      "star_hits": 1.0,
      "season_number": 12,
      "points": 9.0,
      "hat_trick": 1,
      "goals_in_game": 4.0,
      "assists_in_game": 3.0,
      "points_in_game": 7.0,
      "bruiser": 0.1
    },
    {
      "star": "ECKER (S7)",
      "star_goals": 8.0,
      "star_assists": 4.0,
      "star_hits": 11.0,
      "season_number": 28,
      "points": 12.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 5.0,
      "bruiser": 0.9
    },
    {
      "star": "ECKER (S8)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 7.0,
      "season_number": 8,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 2.3
    },
    {
      "star": "ECKER (S9)",
      "star_goals": 5.0,
      "star_assists": 1.0,
      "star_hits": 6.0,
      "season_number": 18,
      "points": 6.0,
      "hat_trick": 1,
      "goals_in_game": 4.0,
      "assists_in_game": 1.0,
      "points_in_game": 4.0,
      "bruiser": 1.0
    },
    {
      "star": "ENGLUND (S1)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 1,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 0.0
    },
    {
      "star": "ENGLUND (S4)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 1.0,
      "season_number": 4,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.5
    },
    {
      "star": "ENGLUND (S7)",
      "star_goals": 0.0,
      "star_assists": 2.0,
      "star_hits": 1.0,
      "season_number": 7,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 0.0,
      "assists_in_game": 2.0,
      "points_in_game": 2.0,
      "bruiser": 0.5
    },
    {
      "star": "FUCHS (S1)",
      "star_goals": 3.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "FUCHS (S5)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 5,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 0.0
    },
    {
      "star": "FUCHS (S8)",
      "star_goals": 1.0,
      "star_assists": 3.0,
      "star_hits": 1.0,
      "season_number": 8,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.2
    },
    {
      "star": "HABERSTICH (S2)",
      "star_goals": 4.0,
      "star_assists": 3.0,
      "star_hits": 2.0,
      "season_number": 6,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.3
    },
    {
      "star": "HABERSTICH (S3)",
      "star_goals": 0.0,
      "star_assists": 3.0,
      "star_hits": 0.0,
      "season_number": 3,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 0.0,
      "assists_in_game": 3.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "HABERSTICH (S8)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 1.0,
      "season_number": 8,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.3
    },
    {
      "star": "HABERSTITCH (S1)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 1,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 0.0
    },
    {
      "star": "HABERSTITCH (S3)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 3,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "HIRANO (S1)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 1,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "HIRANO (S5)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 2.0,
      "season_number": 5,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 1.0
    },
    {
      "star": "HIRANO (S7)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 2.0,
      "season_number": 7,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.0
    },
    {
      "star": "HIRANO (S8)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 8,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "JEROFEJEVS (S4)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 2.0,
      "season_number": 4,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.7
    },
    {
      "star": "JEVPALOVS (S8)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 8,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "JEVPALOVS (S9)",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 3.0,
      "season_number": 18,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.6
    },
    {
      "star": "KATO (S3)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 1.0,
      "season_number": 3,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.3
    },
    {
      "star": "KOBAYASHI (S9)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 2.0,
      "season_number": 9,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.7
    },
    {
      "star": "NAURIS ZUSEVICS (S3)",
      "star_goals": 2.0,
      "star_assists": 3.0,
      "star_hits": 0.0,
      "season_number": 6,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "NAURIS ZUSEVICS (S6)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 3.0,
      "season_number": 6,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 1.0
    },
    {
      "star": "OUELLET (S3)",
      "star_goals": 2.0,
      "star_assists": 2.0,
      "star_hits": 1.0,
      "season_number": 3,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.2
    },
    {
      "star": "OUELLET (S4)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 1.0,
      "season_number": 4,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 1.0
    },
    {
      "star": "OULLET (S1)",
      "star_goals": 0.0,
      "star_assists": 3.0,
      "star_hits": 0.0,
      "season_number": 1,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 0.0,
      "assists_in_game": 3.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "SIEGENTHALER (S1)",
      "star_goals": 4.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 4.0,
      "hat_trick": 1,
      "goals_in_game": 4.0,
      "assists_in_game": 0.0,
      "points_in_game": 4.0,
      "bruiser": 0.0
    },
    {
      "star": "SUGIHARA (S1)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 1,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "SUGIHARA (S3)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 1.0,
      "season_number": 3,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 0.5
    },
    {
      "star": "TAMARA (S1)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 1,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "TANAKA (S1)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 1,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "TANAKA (S3)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 3.0,
      "season_number": 3,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 3.0
    },
    {
      "star": "TOJI (S1)",
      "star_goals": 8.0,
      "star_assists": 8.0,
      "star_hits": 0.0,
      "season_number": 5,
      "points": 16.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.0
    },
    {
      "star": "TOJI (S2)",
      "star_goals": 15.0,
      "star_assists": 10.0,
      "star_hits": 16.0,
      "season_number": 16,
      "points": 25.0,
      "hat_trick": 2,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 5.0,
      "bruiser": 0.6
    },
    {
      "star": "TOJI (S3)",
      "star_goals": 9.0,
      "star_assists": 17.0,
      "star_hits": 16.0,
      "season_number": 24,
      "points": 26.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 4.0,
      "points_in_game": 5.0,
      "bruiser": 0.6
    },
    {
      "star": "WAKABAYASHI (S1)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 1,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "WAKABAYASHI (S10)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 10,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 0.0
    },
    {
      "star": "WAKABAYASHI (S7)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 7,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 0.0
    },
    {
      "star": "WAKABAYASKI (S3)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 3.0,
      "season_number": 3,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 1.5
    },
    {
      "star": "WAKBAYASKI (S8)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 1.0,
      "season_number": 8,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.3
    },
    {
      "star": "YANDLE (S1)",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "YANDLE (S2)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 3.0,
      "season_number": 2,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 1.5
    },
    {
      "star": "YANDLE (S5)",
      "star_goals": 1.0,
      "star_assists": 4.0,
      "star_hits": 1.0,
      "season_number": 10,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.2
    },
    {
      "star": "YANDLE (S6)",
      "star_goals": 1.0,
      "star_assists": 3.0,
      "star_hits": 0.0,
      "season_number": 6,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.0
    },
    {
      "star": "YANDLE (S7)",
      "star_goals": 2.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 14,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "YANDLE (S8)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 8,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 0.0
    },
    {
      "star": "YOSHIDA (S1)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "YOSHIDA (S8)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 4.0,
      "season_number": 8,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 2.0
    },
    {
      "star": "YOSHIDA (S9)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 9,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    }
  ];