var trapPlayers = [
    {
      "star": "ALZNER",
      "star_goals": 6.0,
      "star_assists": 1.0,
      "star_hits": 2.0,
      "season_number": 13,
      "points": 7.0,
      "hat_trick": 2,
      "goals_in_game": 3.0,
      "assists_in_game": 1.0,
      "points_in_game": 4.0,
      "bruiser": 0.3
    },
    {
      "star": "BALCERS",
      "star_goals": 16.0,
      "star_assists": 9.0,
      "star_hits": 11.0,
      "season_number": 51,
      "points": 25.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.4
    },
    {
      "star": "BICEVSKIS",
      "star_goals": 5.0,
      "star_assists": 9.0,
      "star_hits": 2.0,
      "season_number": 25,
      "points": 14.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 4.0,
      "points_in_game": 5.0,
      "bruiser": 0.1
    },
    {
      "star": "BUKARTS",
      "star_goals": 17.0,
      "star_assists": 12.0,
      "star_hits": 7.0,
      "season_number": 57,
      "points": 29.0,
      "hat_trick": 1,
      "goals_in_game": 5.0,
      "assists_in_game": 3.0,
      "points_in_game": 5.0,
      "bruiser": 0.2
    },
    {
      "star": "BURNS",
      "star_goals": 4.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 4,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "DANO",
      "star_goals": 3.0,
      "star_assists": 3.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.0
    },
    {
      "star": "FREIBERGS",
      "star_goals": 2.0,
      "star_assists": 3.0,
      "star_hits": 1.0,
      "season_number": 12,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.2
    },
    {
      "star": "FRIEBERGS",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 2.0,
      "season_number": 3,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.7
    },
    {
      "star": "GIRGENSONS",
      "star_goals": 45.0,
      "star_assists": 45.0,
      "star_hits": 58.0,
      "season_number": 168,
      "points": 90.0,
      "hat_trick": 6,
      "goals_in_game": 4.0,
      "assists_in_game": 4.0,
      "points_in_game": 7.0,
      "bruiser": 0.6
    },
    {
      "star": "HARDEN",
      "star_goals": 25.0,
      "star_assists": 23.0,
      "star_hits": 23.0,
      "season_number": 91,
      "points": 48.0,
      "hat_trick": 4,
      "goals_in_game": 4.0,
      "assists_in_game": 4.0,
      "points_in_game": 6.0,
      "bruiser": 0.5
    },
    {
      "star": "HENNESSY",
      "star_goals": 4.0,
      "star_assists": 3.0,
      "star_hits": 4.0,
      "season_number": 27,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.6
    },
    {
      "star": "HINOSTROZA",
      "star_goals": 11.0,
      "star_assists": 7.0,
      "star_hits": 6.0,
      "season_number": 55,
      "points": 18.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.3
    },
    {
      "star": "JEVPALOVS",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 4,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "KENINS",
      "star_goals": 5.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 11,
      "points": 7.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.0
    },
    {
      "star": "KOVALCHUK",
      "star_goals": 28.0,
      "star_assists": 27.0,
      "star_hits": 21.0,
      "season_number": 114,
      "points": 55.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 4.0,
      "points_in_game": 4.0,
      "bruiser": 0.4
    },
    {
      "star": "LIPSBERGS",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 4,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "MACEACHERN",
      "star_goals": 7.0,
      "star_assists": 12.0,
      "star_hits": 8.0,
      "season_number": 37,
      "points": 19.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 3.0,
      "bruiser": 0.4
    },
    {
      "star": "MARSHALL",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 4.0,
      "season_number": 8,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 4.0
    },
    {
      "star": "MILANO",
      "star_goals": 5.0,
      "star_assists": 4.0,
      "star_hits": 6.0,
      "season_number": 21,
      "points": 9.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.7
    },
    {
      "star": "ORLOV",
      "star_goals": 9.0,
      "star_assists": 10.0,
      "star_hits": 23.0,
      "season_number": 52,
      "points": 19.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 1.2
    },
    {
      "star": "OULLET",
      "star_goals": 2.0,
      "star_assists": 5.0,
      "star_hits": 1.0,
      "season_number": 15,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.1
    },
    {
      "star": "OVECHKIN",
      "star_goals": 27.0,
      "star_assists": 21.0,
      "star_hits": 40.0,
      "season_number": 47,
      "points": 48.0,
      "hat_trick": 3,
      "goals_in_game": 3.0,
      "assists_in_game": 4.0,
      "points_in_game": 5.0,
      "bruiser": 0.8
    },
    {
      "star": "PARAYKO",
      "star_goals": 18.0,
      "star_assists": 22.0,
      "star_hits": 26.0,
      "season_number": 77,
      "points": 40.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 4.0,
      "points_in_game": 5.0,
      "bruiser": 0.7
    },
    {
      "star": "PIETRANGELO",
      "star_goals": 6.0,
      "star_assists": 3.0,
      "star_hits": 17.0,
      "season_number": 9,
      "points": 9.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 1.9
    },
    {
      "star": "SNUGGERUD",
      "star_goals": 2.0,
      "star_assists": 4.0,
      "star_hits": 2.0,
      "season_number": 8,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.3
    },
    {
      "star": "TARASENKO",
      "star_goals": 35.0,
      "star_assists": 47.0,
      "star_hits": 62.0,
      "season_number": 172,
      "points": 82.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 5.0,
      "points_in_game": 6.0,
      "bruiser": 0.8
    },
    {
      "star": "TOJI",
      "star_goals": 25.0,
      "star_assists": 28.0,
      "star_hits": 21.0,
      "season_number": 98,
      "points": 53.0,
      "hat_trick": 3,
      "goals_in_game": 3.0,
      "assists_in_game": 5.0,
      "points_in_game": 7.0,
      "bruiser": 0.4
    },
    {
      "star": "VARAKAS",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 2.0,
      "season_number": 4,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 2.0
    },
    {
      "star": "YANDLE",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    }
  ];

var trapSeason = [
    {
      "star": "ALZNER (S6)",
      "star_goals": 3.0,
      "star_assists": 0.0,
      "star_hits": 1.0,
      "season_number": 6,
      "points": 3.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 0.0,
      "points_in_game": 3.0,
      "bruiser": 0.3
    },
    {
      "star": "ALZNER (S7)",
      "star_goals": 3.0,
      "star_assists": 1.0,
      "star_hits": 1.0,
      "season_number": 7,
      "points": 4.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 1.0,
      "points_in_game": 4.0,
      "bruiser": 0.2
    },
    {
      "star": "BALCERS (S3)",
      "star_goals": 6.0,
      "star_assists": 3.0,
      "star_hits": 5.0,
      "season_number": 12,
      "points": 9.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.6
    },
    {
      "star": "BALCERS (S4)",
      "star_goals": 2.0,
      "star_assists": 3.0,
      "star_hits": 1.0,
      "season_number": 8,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.2
    },
    {
      "star": "BALCERS (S6)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 2.0,
      "season_number": 6,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 1.0
    },
    {
      "star": "BALCERS (S7)",
      "star_goals": 3.0,
      "star_assists": 0.0,
      "star_hits": 1.0,
      "season_number": 7,
      "points": 3.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 0.0,
      "points_in_game": 3.0,
      "bruiser": 0.3
    },
    {
      "star": "BALCERS (S9)",
      "star_goals": 3.0,
      "star_assists": 3.0,
      "star_hits": 2.0,
      "season_number": 18,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.3
    },
    {
      "star": "BICEVSKIS (S3)",
      "star_goals": 1.0,
      "star_assists": 4.0,
      "star_hits": 0.0,
      "season_number": 3,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 4.0,
      "points_in_game": 5.0,
      "bruiser": 0.0
    },
    {
      "star": "BICEVSKIS (S5)",
      "star_goals": 3.0,
      "star_assists": 4.0,
      "star_hits": 1.0,
      "season_number": 15,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 3.0,
      "bruiser": 0.1
    },
    {
      "star": "BICEVSKIS (S7)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 1.0,
      "season_number": 7,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.5
    },
    {
      "star": "BUKARTS (S2)",
      "star_goals": 1.0,
      "star_assists": 3.0,
      "star_hits": 2.0,
      "season_number": 2,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.5
    },
    {
      "star": "BUKARTS (S3)",
      "star_goals": 6.0,
      "star_assists": 2.0,
      "star_hits": 2.0,
      "season_number": 6,
      "points": 8.0,
      "hat_trick": 1,
      "goals_in_game": 5.0,
      "assists_in_game": 2.0,
      "points_in_game": 5.0,
      "bruiser": 0.2
    },
    {
      "star": "BUKARTS (S4)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 1.0,
      "season_number": 4,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 0.5
    },
    {
      "star": "BUKARTS (S5)",
      "star_goals": 3.0,
      "star_assists": 4.0,
      "star_hits": 0.0,
      "season_number": 10,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 5.0,
      "bruiser": 0.0
    },
    {
      "star": "BUKARTS (S8)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 8,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "BUKARTS (S9)",
      "star_goals": 4.0,
      "star_assists": 2.0,
      "star_hits": 2.0,
      "season_number": 27,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.3
    },
    {
      "star": "BURNS (S1)",
      "star_goals": 4.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 4,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "DANO (S1)",
      "star_goals": 3.0,
      "star_assists": 3.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.0
    },
    {
      "star": "FREIBERGS (S4)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 4,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "FREIBERGS (S8)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 1.0,
      "season_number": 8,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.3
    },
    {
      "star": "FRIEBERGS (S3)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 2.0,
      "season_number": 3,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.7
    },
    {
      "star": "GIRGENSONS (S1)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 3,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "GIRGENSONS (S2)",
      "star_goals": 1.0,
      "star_assists": 3.0,
      "star_hits": 8.0,
      "season_number": 4,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 2.0,
      "bruiser": 2.0
    },
    {
      "star": "GIRGENSONS (S3)",
      "star_goals": 9.0,
      "star_assists": 8.0,
      "star_hits": 17.0,
      "season_number": 18,
      "points": 17.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 5.0,
      "bruiser": 1.0
    },
    {
      "star": "GIRGENSONS (S4)",
      "star_goals": 5.0,
      "star_assists": 2.0,
      "star_hits": 3.0,
      "season_number": 8,
      "points": 7.0,
      "hat_trick": 1,
      "goals_in_game": 4.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.4
    },
    {
      "star": "GIRGENSONS (S6)",
      "star_goals": 5.0,
      "star_assists": 6.0,
      "star_hits": 3.0,
      "season_number": 12,
      "points": 11.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 4.0,
      "points_in_game": 7.0,
      "bruiser": 0.3
    },
    {
      "star": "GIRGENSONS (S7)",
      "star_goals": 6.0,
      "star_assists": 2.0,
      "star_hits": 4.0,
      "season_number": 21,
      "points": 8.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 1.0,
      "points_in_game": 4.0,
      "bruiser": 0.5
    },
    {
      "star": "GIRGENSONS (S8)",
      "star_goals": 10.0,
      "star_assists": 11.0,
      "star_hits": 10.0,
      "season_number": 48,
      "points": 21.0,
      "hat_trick": 2,
      "goals_in_game": 3.0,
      "assists_in_game": 3.0,
      "points_in_game": 6.0,
      "bruiser": 0.5
    },
    {
      "star": "GIRGENSONS (S9)",
      "star_goals": 7.0,
      "star_assists": 12.0,
      "star_hits": 13.0,
      "season_number": 54,
      "points": 19.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 5.0,
      "bruiser": 0.7
    },
    {
      "star": "HARDEN (S4)",
      "star_goals": 5.0,
      "star_assists": 8.0,
      "star_hits": 4.0,
      "season_number": 12,
      "points": 13.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 3.0,
      "points_in_game": 6.0,
      "bruiser": 0.3
    },
    {
      "star": "HARDEN (S5)",
      "star_goals": 9.0,
      "star_assists": 3.0,
      "star_hits": 2.0,
      "season_number": 15,
      "points": 12.0,
      "hat_trick": 2,
      "goals_in_game": 4.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.2
    },
    {
      "star": "HARDEN (S6)",
      "star_goals": 2.0,
      "star_assists": 4.0,
      "star_hits": 7.0,
      "season_number": 12,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 4.0,
      "points_in_game": 4.0,
      "bruiser": 1.2
    },
    {
      "star": "HARDEN (S7)",
      "star_goals": 0.0,
      "star_assists": 2.0,
      "star_hits": 2.0,
      "season_number": 7,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 0.0,
      "assists_in_game": 2.0,
      "points_in_game": 2.0,
      "bruiser": 1.0
    },
    {
      "star": "HARDEN (S9)",
      "star_goals": 9.0,
      "star_assists": 6.0,
      "star_hits": 8.0,
      "season_number": 45,
      "points": 15.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 4.0,
      "points_in_game": 5.0,
      "bruiser": 0.5
    },
    {
      "star": "HENNESSY (S9)",
      "star_goals": 4.0,
      "star_assists": 3.0,
      "star_hits": 4.0,
      "season_number": 27,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.6
    },
    {
      "star": "HINOSTROZA (S7)",
      "star_goals": 5.0,
      "star_assists": 2.0,
      "star_hits": 4.0,
      "season_number": 21,
      "points": 7.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.6
    },
    {
      "star": "HINOSTROZA (S8)",
      "star_goals": 3.0,
      "star_assists": 3.0,
      "star_hits": 0.0,
      "season_number": 16,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "HINOSTROZA (S9)",
      "star_goals": 3.0,
      "star_assists": 2.0,
      "star_hits": 2.0,
      "season_number": 18,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.4
    },
    {
      "star": "JEVPALOVS (S1)",
      "star_goals": 0.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 0.0,
      "hat_trick": 0,
      "goals_in_game": 0.0,
      "assists_in_game": 0.0,
      "points_in_game": 0.0,
      "bruiser": null
    },
    {
      "star": "JEVPALOVS (S2)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "KENINS (S2)",
      "star_goals": 3.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 3.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 0.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "KENINS (S9)",
      "star_goals": 2.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 9,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.0
    },
    {
      "star": "KOVALCHUK (S5)",
      "star_goals": 9.0,
      "star_assists": 6.0,
      "star_hits": 3.0,
      "season_number": 25,
      "points": 15.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.2
    },
    {
      "star": "KOVALCHUK (S6)",
      "star_goals": 1.0,
      "star_assists": 5.0,
      "star_hits": 4.0,
      "season_number": 12,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 4.0,
      "points_in_game": 4.0,
      "bruiser": 0.7
    },
    {
      "star": "KOVALCHUK (S7)",
      "star_goals": 18.0,
      "star_assists": 16.0,
      "star_hits": 14.0,
      "season_number": 77,
      "points": 34.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 4.0,
      "points_in_game": 4.0,
      "bruiser": 0.4
    },
    {
      "star": "LIPSBERGS (S4)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 4,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "MACEACHERN (S2)",
      "star_goals": 2.0,
      "star_assists": 4.0,
      "star_hits": 3.0,
      "season_number": 4,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.5
    },
    {
      "star": "MACEACHERN (S3)",
      "star_goals": 1.0,
      "star_assists": 3.0,
      "star_hits": 2.0,
      "season_number": 6,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 3.0,
      "bruiser": 0.5
    },
    {
      "star": "MACEACHERN (S5)",
      "star_goals": 2.0,
      "star_assists": 2.0,
      "star_hits": 2.0,
      "season_number": 10,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.5
    },
    {
      "star": "MACEACHERN (S8)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 1.0,
      "season_number": 8,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.5
    },
    {
      "star": "MACEACHERN (S9)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 9,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "MARSHALL (S8)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 4.0,
      "season_number": 8,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 4.0
    },
    {
      "star": "MILANO (S4)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 4,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "MILANO (S5)",
      "star_goals": 2.0,
      "star_assists": 0.0,
      "star_hits": 1.0,
      "season_number": 5,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 0.0,
      "points_in_game": 2.0,
      "bruiser": 0.5
    },
    {
      "star": "MILANO (S6)",
      "star_goals": 2.0,
      "star_assists": 3.0,
      "star_hits": 5.0,
      "season_number": 12,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 1.0
    },
    {
      "star": "ORLOV (S5)",
      "star_goals": 4.0,
      "star_assists": 4.0,
      "star_hits": 7.0,
      "season_number": 15,
      "points": 8.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.9
    },
    {
      "star": "ORLOV (S6)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 1.0,
      "season_number": 6,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.3
    },
    {
      "star": "ORLOV (S7)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 7.0,
      "season_number": 7,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 3.5
    },
    {
      "star": "ORLOV (S8)",
      "star_goals": 3.0,
      "star_assists": 3.0,
      "star_hits": 8.0,
      "season_number": 24,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 1.3
    },
    {
      "star": "OULLET (S6)",
      "star_goals": 1.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 6,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 0.0
    },
    {
      "star": "OULLET (S9)",
      "star_goals": 1.0,
      "star_assists": 3.0,
      "star_hits": 1.0,
      "season_number": 9,
      "points": 4.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.2
    },
    {
      "star": "OVECHKIN (S1)",
      "star_goals": 5.0,
      "star_assists": 2.0,
      "star_hits": 0.0,
      "season_number": 8,
      "points": 7.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 5.0,
      "bruiser": 0.0
    },
    {
      "star": "OVECHKIN (S2)",
      "star_goals": 10.0,
      "star_assists": 4.0,
      "star_hits": 21.0,
      "season_number": 10,
      "points": 14.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 1.5
    },
    {
      "star": "OVECHKIN (S3)",
      "star_goals": 8.0,
      "star_assists": 12.0,
      "star_hits": 11.0,
      "season_number": 21,
      "points": 20.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 4.0,
      "points_in_game": 5.0,
      "bruiser": 0.6
    },
    {
      "star": "OVECHKIN (S4)",
      "star_goals": 4.0,
      "star_assists": 3.0,
      "star_hits": 8.0,
      "season_number": 8,
      "points": 7.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 1.1
    },
    {
      "star": "PARAYKO (S1)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "PARAYKO (S4)",
      "star_goals": 2.0,
      "star_assists": 1.0,
      "star_hits": 1.0,
      "season_number": 4,
      "points": 3.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 0.3
    },
    {
      "star": "PARAYKO (S5)",
      "star_goals": 4.0,
      "star_assists": 5.0,
      "star_hits": 7.0,
      "season_number": 15,
      "points": 9.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.8
    },
    {
      "star": "PARAYKO (S6)",
      "star_goals": 2.0,
      "star_assists": 4.0,
      "star_hits": 5.0,
      "season_number": 12,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 4.0,
      "points_in_game": 4.0,
      "bruiser": 0.8
    },
    {
      "star": "PARAYKO (S7)",
      "star_goals": 7.0,
      "star_assists": 7.0,
      "star_hits": 6.0,
      "season_number": 28,
      "points": 14.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 5.0,
      "bruiser": 0.4
    },
    {
      "star": "PARAYKO (S8)",
      "star_goals": 1.0,
      "star_assists": 4.0,
      "star_hits": 7.0,
      "season_number": 16,
      "points": 5.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 1.4
    },
    {
      "star": "PIETRANGELO (S2)",
      "star_goals": 5.0,
      "star_assists": 3.0,
      "star_hits": 13.0,
      "season_number": 6,
      "points": 8.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 1.0,
      "points_in_game": 3.0,
      "bruiser": 1.6
    },
    {
      "star": "PIETRANGELO (S3)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 4.0,
      "season_number": 3,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 4.0
    },
    {
      "star": "SNUGGERUD (S1)",
      "star_goals": 0.0,
      "star_assists": 0.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 0.0,
      "hat_trick": 0,
      "goals_in_game": 0.0,
      "assists_in_game": 0.0,
      "points_in_game": 0.0,
      "bruiser": null
    },
    {
      "star": "SNUGGERUD (S3)",
      "star_goals": 2.0,
      "star_assists": 4.0,
      "star_hits": 2.0,
      "season_number": 6,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.3
    },
    {
      "star": "TARASENKO (S1)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 5,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    },
    {
      "star": "TARASENKO (S2)",
      "star_goals": 2.0,
      "star_assists": 4.0,
      "star_hits": 15.0,
      "season_number": 6,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 2.5
    },
    {
      "star": "TARASENKO (S4)",
      "star_goals": 3.0,
      "star_assists": 5.0,
      "star_hits": 3.0,
      "season_number": 8,
      "points": 8.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 5.0,
      "points_in_game": 6.0,
      "bruiser": 0.4
    },
    {
      "star": "TARASENKO (S5)",
      "star_goals": 8.0,
      "star_assists": 9.0,
      "star_hits": 5.0,
      "season_number": 25,
      "points": 17.0,
      "hat_trick": 1,
      "goals_in_game": 3.0,
      "assists_in_game": 4.0,
      "points_in_game": 5.0,
      "bruiser": 0.3
    },
    {
      "star": "TARASENKO (S6)",
      "star_goals": 2.0,
      "star_assists": 4.0,
      "star_hits": 6.0,
      "season_number": 12,
      "points": 6.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 2.0,
      "points_in_game": 3.0,
      "bruiser": 1.0
    },
    {
      "star": "TARASENKO (S7)",
      "star_goals": 12.0,
      "star_assists": 10.0,
      "star_hits": 18.0,
      "season_number": 56,
      "points": 22.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 2.0,
      "points_in_game": 4.0,
      "bruiser": 0.8
    },
    {
      "star": "TARASENKO (S8)",
      "star_goals": 3.0,
      "star_assists": 8.0,
      "star_hits": 5.0,
      "season_number": 24,
      "points": 11.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 4.0,
      "bruiser": 0.5
    },
    {
      "star": "TARASENKO (S9)",
      "star_goals": 4.0,
      "star_assists": 6.0,
      "star_hits": 10.0,
      "season_number": 36,
      "points": 10.0,
      "hat_trick": 0,
      "goals_in_game": 2.0,
      "assists_in_game": 3.0,
      "points_in_game": 3.0,
      "bruiser": 1.0
    },
    {
      "star": "TOJI (S7)",
      "star_goals": 25.0,
      "star_assists": 28.0,
      "star_hits": 21.0,
      "season_number": 98,
      "points": 53.0,
      "hat_trick": 3,
      "goals_in_game": 3.0,
      "assists_in_game": 5.0,
      "points_in_game": 7.0,
      "bruiser": 0.4
    },
    {
      "star": "VARAKAS (S4)",
      "star_goals": 1.0,
      "star_assists": 0.0,
      "star_hits": 2.0,
      "season_number": 4,
      "points": 1.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 0.0,
      "points_in_game": 1.0,
      "bruiser": 2.0
    },
    {
      "star": "YANDLE (S2)",
      "star_goals": 1.0,
      "star_assists": 1.0,
      "star_hits": 0.0,
      "season_number": 2,
      "points": 2.0,
      "hat_trick": 0,
      "goals_in_game": 1.0,
      "assists_in_game": 1.0,
      "points_in_game": 2.0,
      "bruiser": 0.0
    }
  ];